
Tryign to edit .......................................................................


P.when("A","jQuery").register("imageBlockLogger",function(A,$){window.ImageBlockclientLogger=function(feature,forceUpload){var self=this,data={},vips={"www.amazon.com":"fls-na","devo":"fls-devo.vipinteg"};
self.logSingleton=function(key){data[key]=1;
};
self.logHit=function(key){if(!data[key]){data[key]=1;
}else{data[key]++;
}};
self.logKeyValuePair=function(key,value){data[key]=value;
};
self.deleteKey=function(key){if(data[key]){delete data[key];
}};
self.startTimer=function(key){data[key]=+new Date();
};
self.endTimer=function(key){if(data[key]){data[key]=+new Date()-data[key];
}};
self.upload=function(){var protocol=location.protocol=="https:"?"https://":"http://",vip=vips[location.host]||vips.devo,url=protocol+vip+".amazon.com/1/softlines/1/OP/"+feature+"?"+$.param(data)+"&_="+(+new Date());
(new Image()).src=url;
};
if(forceUpload){$(window).unload(function(){self.upload();
});
}};
});
P.when("A","jQuery").register("imageBlockUtils",function(A,$){var utils={},options,colorToVideo,captionTimeout,landingColor,colorImages,windowResized=false,itemContainer=$("#main-image-container");
utils.setLandingColor=function(c){landingColor=c;
};
utils.resizeHappened=function(){windowResized=true;
};
utils.stopLastPlayingVideo=function(){if(AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId]){try{AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId].stop();
}catch(e){}}AmznVideoPlayer.hideAll();
};
utils.getMainBlockHeight=function(){var containerElem=itemContainer.get(0);
var height=0;
if(typeof containerElem!=="undefined"){if(!windowResized){height=containerElem.style.height;
}else{var width=containerElem.offsetWidth;
height=width/options.holderRatio;
height=height>options.holderMaxHeight?options.holderMaxHeight:height;
}}return height;
};
utils.loadImageManually=function(images,ctx){$(images,ctx).each(function(){var $t=$(this);
if(!$t.attr("data-a-image-already-loaded")){$t.attr("data-a-image-already-loaded",true);
var dynamicUrl=utils.loadDynamicImage($t);
var $img=$("<img>").attr("src",dynamicUrl||$t.data("a-image-source"));
$img.attr("data-a-hires",$t.data("a-hires"));
$img.attr("data-old-hires",$t.data("old-hires"));
$img.attr("data-a-manual-replacement",$t.data("a-manual-replacement"));
$img.attr("data-a-dynamic-image",JSON.stringify($t.data("a-dynamic-image")));
var classes="";
classes+=$t.attr("class");
var extraClasses=$t.data("a-extra-classes");
if(extraClasses){classes+=" "+extraClasses;
}$img.attr("class",classes);
$img.attr("id",$t.attr("id"));
$img.attr("style",$t.attr("style"));
$t.replaceWith($img);
}});
};
utils.loadDynamicImage=function(image){var $image=$(image);
var sizes=$image.data("a-dynamic-image");
if(!sizes||typeof sizes!=="object"){return;
}var $container=$image.data("a-dynamic-image-container");
if(typeof $container==="undefined"){$container=$image.parents(".a-dynamic-image-container");
if($container.length===0){$container=$image.parent();
}$image.data("a-dynamic-image-container",$container);
}var pixelRatio=window.devicePixelRatio?window.devicePixelRatio:1;
var width=$container.width()*pixelRatio;
var height=$container.height()*pixelRatio;
var closestSizeDiff=Number.MAX_VALUE;
var closestLargerSizeDiff=Number.MAX_VALUE;
var closestUrl=$image.attr("src")||"";
var closestLargerUrl;
var aspectRatio=width/height;
$.each(sizes,function(url,size){var proposedHeight=parseInt(size[0],10);
var proposedWidth=parseInt(size[1],10);
var heightDiff=proposedHeight-height;
var widthDiff=proposedWidth-width;
var sizeDiff=aspectRatio>=1?widthDiff:heightDiff;
if(Math.abs(sizeDiff)<closestLargerSizeDiff&&sizeDiff>=0){closestLargerSizeDiff=Math.abs(sizeDiff);
closestLargerUrl=url;
}if(Math.abs(sizeDiff)<closestSizeDiff){closestSizeDiff=Math.abs(sizeDiff);
closestUrl=url;
}});
if(closestLargerUrl){closestUrl=closestLargerUrl;
}return closestUrl;
};
function fetchChildVideos(color){var obj=options.colorToAsin[color];
if(!(obj&&obj.asin)){return;
}$.ajax({url:"/gp/product/features/apparel-main-image/videos.html",data:{asin:obj.asin,productGroupID:options.productGroupID,useChromelessVideoPlayer:options.useChromelessVideoPlayer,isUDP:options.isUDP},dataType:"json",timeout:4000,success:function(data){if(data){colorToVideo[color]=data;
A.trigger("image-block-video-fetch-completed",color);
}}});
}utils.getVideos=function(color){if(options.useChildVideos){if(color==landingColor){color=options.defaultColor;
}if(!colorToVideo[color]){colorToVideo[color]=[];
fetchChildVideos(color);
}return colorToVideo[color];
}return options.videos;
};
utils.getBestUrlForAvailableWidth=function(dynamicImages){var maxWidth=0;
var bestSlateImage;
$.each(dynamicImages,function(url,size){if(size[0]>maxWidth){bestSlateImage=url;
maxWidth=size[0];
}});
return bestSlateImage;
};
utils.getMaxWidthOfSlateImages=function(dynamicImages){var maxWidth=0;
$.each(dynamicImages,function(url,size){if(size[0]>maxWidth){maxWidth=size[0];
}});
return maxWidth;
};
utils.getMaxHeightOfSlateImages=function(dynamicImages){var maxHeight=0;
$.each(dynamicImages,function(url,size){if(size[1]>maxHeight){maxHeight=size[1];
}});
return maxHeight;
};
utils.getMaxWidthOfMainImage=function(mainImageHash){var maxWidth=itemContainer.width();
var imageWidth=utils.getMaxWidthOfSlateImages(mainImageHash);
if(imageWidth>0){maxWidth=Math.min(maxWidth,imageWidth);
}return maxWidth;
};
utils.getMaxHeightOfMainImage=function(mainImageHash){var maxHeight=itemContainer.height();
var imageHeight=utils.getMaxHeightOfSlateImages(mainImageHash);
if(imageHeight>0){maxHeight=Math.min(maxHeight,imageHeight);
}return maxHeight;
};
utils.getColorFromState=function(variationsState){if(!variationsState){return;
}var colorName="";
var variationLabels=DetailPage.StateController.getState()["variation_display_labels"];
$.each(options.visualDimensions,function(i,dim){var label=(options.gIsNewTwister==1)?dim:variationLabels[dim];
if(variationsState[label]){colorName+=" "+variationsState[label];
}});
return colorName&&colorName.substring(1);
};
utils.isBuyableVariation=function(dpState){if(!dpState.current_hovered_asin){var numDims=dpState.num_variation_dimensions;
return dpState.num_dimensions_selected!=numDims&&dpState.num_dimensions_hovered!=numDims;
}return true;
};
utils.showUnavailableExp=function(unavailableColor){if(unavailableColor){$("#imageBlock .unvailableVariation").html(unavailableColor);
$("#imageBlock .variationUnavailable").show();
}};
utils.hideUnavailableExp=function(){$("#imageBlock .unavailableExp").hide();
};
utils.splitByType=function(c,type,index,thumbnailIndex,imageCallback,videoCallback,ciuCallback,mouseIn){switch(type){case"image":return imageCallback(c,index,mouseIn);
case"chromeful-video":return videoCallback(c,index);
default:return{};
}};
utils.setImageCaption=function(c,type,index,thumbnailIndex,timeout,mouseIn){if(captionTimeout){clearTimeout(captionTimeout);
}captionTimeout=null;
if(timeout){captionTimeout=setTimeout(function(){utils.setImageCaption(c,type,thumbnailIndex);
},timeout);
}function imageCallback(c,i,mouseIn){if(mouseIn&&options.useIV){return options.staticStrings["clickToExpand"];
}else{if(colorImages[c]&&colorImages[c][i].hiRes&&options.useHoverZoom){if(options.hoverZoomIndicator&&options.useHoverZoomIpad){return"<img src='"+options.staticImages.hoverZoomIcon+"'/>&nbsp;"+options.staticStrings["touchToZoom"];
}else{if(options.useHoverZoomIpad){return options.staticStrings["touchToZoom"];
}else{if(options.hoverZoomIndicator){return"<img src='"+options.staticImages.hoverZoomIcon+"'/>&nbsp;"+options.staticStrings["rollOverToZoom"];
}else{return options.staticStrings["rollOverToZoom"];
}}}}else{if(options.useIV){return options.staticStrings["clickToExpand"];
}else{return"";
}}}}function videoCallback(c,i){if(!options.useChromelessVideoPlayer){return options.staticStrings["playVideo"];
}}function ciuCallback(i){return options.customerImages[i].caption;
}var caption=utils.splitByType(c,type,index,thumbnailIndex,imageCallback,videoCallback,ciuCallback,mouseIn)||"&nbsp;";
$("#canvasCaption").html(caption);
};
utils.getSlateImage=function(color){return options.useChildVideos&&options.colorToAsin[color].slate[0];
};
utils.init=function(opts){utils.options=options=opts;
colorImages=options.colorImages;
landingColor=options.landingColor||options.defaultColor;
colorToVideo={};
colorToVideo[options.defaultColor]=options.videos;
return utils;
};
if(typeof JSON!=="object"){JSON={};
}(function(){function f(n){return n<10?"0"+n:n;
}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf();
};
}var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},rep;
function quote(string){escapable.lastIndex=0;
return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];
return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+string+'"';
}function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];
if(value&&typeof value==="object"&&typeof value.toJSON==="function"){value=value.toJSON(key);
}if(typeof rep==="function"){value=rep.call(holder,key,value);
}switch(typeof value){case"string":return quote(value);
case"number":return isFinite(value)?String(value):"null";
case"boolean":case"null":return String(value);
case"object":if(!value){return"null";
}gap+=indent;
partial=[];
if(Object.prototype.toString.apply(value)==="[object Array]"){length=value.length;
for(i=0;
i<length;
i+=1){partial[i]=str(i,value)||"null";
}v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";
gap=mind;
return v;
}if(rep&&typeof rep==="object"){length=rep.length;
for(i=0;
i<length;
i+=1){if(typeof rep[i]==="string"){k=rep[i];
v=str(k,value);
if(v){partial.push(quote(k)+(gap?": ":":")+v);
}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);
if(v){partial.push(quote(k)+(gap?": ":":")+v);
}}}}v=partial.length===0?"{}":gap?"{\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";
gap=mind;
return v;
}}if(typeof JSON.stringify!=="function"){JSON.stringify=function(value,replacer,space){var i;
gap="";
indent="";
if(typeof space==="number"){for(i=0;
i<space;
i+=1){indent+=" ";
}}else{if(typeof space==="string"){indent=space;
}}rep=replacer;
if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number")){throw new Error("JSON.stringify");
}return str("",{"":value});
};
}if(typeof JSON.parse!=="function"){JSON.parse=function(text,reviver){var j;
function walk(holder,key){var k,v,value=holder[key];
if(value&&typeof value==="object"){for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=walk(value,k);
if(v!==undefined){value[k]=v;
}else{delete value[k];
}}}}return reviver.call(holder,key,value);
}text=String(text);
cx.lastIndex=0;
if(cx.test(text)){text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4);
});
}if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");
return typeof reviver==="function"?walk({"":j},""):j;
}throw new SyntaxError("JSON.parse");
};
}}());
return utils;
});
P.when("A","jQuery").register("imageMagnifier",function(A,$){function hoverZoomBoundInDPX(){var b={left:Infinity,top:Infinity,right:-Infinity,bottom:-Infinity};
var lc=$("#leftCol"),cc=$("#centerCol"),ccHze=$("#hover-zoom-end");
b.top=cc.offset().top;
b.left=lc.offset().left+lc.outerWidth();
b.right=$("#rightCol").offset().left;
b.bottom=cc.outerHeight()+b.top;
if(ccHze&&ccHze.offset().top>b.bottom){b.bottom=ccHze.offset().top;
}return b;
}function parseMediaServerCodes(url){var m=url.match(/\._((\w|,|\.)+)_\.(gif|jpg|png)$/i);
var codes={};
if(m){var mediaServerCodes=m[1].split("_");
for(var i=0;
i<mediaServerCodes.length;
i++){var m2=mediaServerCodes[i].match(/^([A-Z]+)(\d+(\.\d+)?)$/);
if(m2){codes[m2[1]]=Number(m2[2]);
}}}return codes;
}$.fn.amazonMagnifier=function(options){var navImage=this;
var defaultOptions={detailImageUrl:navImage.attr("data-old-hires"),location:"over",locationElement:navImage,prelaod:"ready",zIndex:50};
options=$.extend(defaultOptions,options);
options.adjustment=[10,0,-10,0];
var zoomWindow=null;
var lens=null;
var cursorAt=null;
var navImageRect=null;
var preloaded={"null":1,"":1,"undefined":1};
var engaged=false;
var magnifierSuppressed=false;
var currentDetailImageUrl=options.detailImageUrl;
var isIE6=$.browser.msie&&parseInt($.browser.version)<=6;
var hiddenSelects;
var hoverZoomIpad=options.useHoverZoomIpad||0;
var hoverOnLoad=0;
var urlsLogged={};
var Lens=function(){var self=this;
var size=[0,0];
var zoomRatio=(zoomWindow.detailSize&&zoomWindow.detailSize[0]||500000000)/navImageRect[2];
var zoomHtRatio=(zoomWindow.detailSize&&zoomWindow.detailSize[1]||500000000)/navImageRect[3];
if(zoomHtRatio>zoomRatio){zoomRatio=zoomHtRatio;
}$("#magnifierLens").remove();
var jq=$("<div id='magnifierLens' />").css({backgroundImage:"url("+options.generalImageUrls.zoomLensBackground+")",position:"absolute",cursor:"pointer"});
function updateSize(ratio){var width=Math.round(Math.min(navImage.width(),zoomWindow.rect.width/ratio));
var height=Math.round(Math.min(navImage.height(),zoomWindow.rect.height/ratio));
jq.css({width:width,height:height});
size=[width,height];
}self.updatePosition=function(){var range=[navImageRect[2]-size[0],navImageRect[3]-size[1]];
var u=range[0]<=0?0.5:Math.max(0,Math.min(1,(cursorAt[0]-size[0]/2-navImageRect[0]-self.offset.left)/range[0]));
var v=range[1]<=0?0.5:Math.max(0,Math.min(1,(cursorAt[1]-size[1]/2-navImageRect[1]-self.offset.top)/range[1]));
var x=navImageRect[0]+Math.round(u*range[0]);
var y=navImageRect[1]+Math.round(v*range[1]);
jq.get(0).style.left=x+"px";
jq.get(0).style.top=y+"px";
return[u,v];
};
self.destroy=function(){jq.remove();
};
self.offset=navImage.offsetParent().offset();
updateSize(zoomRatio);
self.updatePosition();
jq.appendTo(navImage.parent());
if(!zoomWindow.detailImage[0].complete){zoomWindow.detailImage.load(function(){var zoomRatio=zoomWindow.detailImage.width()/navImageRect[2];
updateSize(zoomRatio);
self.updatePosition();
});
}};
Lens.preload=function(){navImage.preload(options.generalImageUrls.lensBackgroundUrl);
};
var ZoomWindow=function(){var zw=this;
var adjustment=options.adjustment;
$("#zoomWindow").remove();
var cropWindow=$("<div id='zoomWindow' />").css({overflow:"hidden",position:"absolute",backgroundColor:"white",zIndex:options.zIndex});
function fit(){var rect=new Object();
if(options.location=="over"){if($("#centerCol").length>0){rect=hoverZoomBoundInDPX();
}else{if($(".productImageGrid").length>0){rect=hoverZoomBound();
}else{rect.left=0;
rect.right=0;
}}}else{if(options.location=="right"){var o=navImage.offset();
rect={left:o.left+navImage.outerWidth(),top:o.top,right:o.left+navImage.outerWidth()+400,bottom:o.top+400};
}}if(options.minHeightElement){rect.bottom=Math.max(rect.bottom,rect.top+$(options.minHeightElement).outerHeight());
}rect.bottom=Math.min(rect.bottom,$(window).scrollTop()+$(window).height());
rect.left+=adjustment[0];
rect.top+=adjustment[1];
rect.right+=adjustment[2];
rect.bottom+=adjustment[3];
rect.width=rect.right-rect.left;
rect.height=rect.bottom-rect.top;
cropWindow.css({left:rect.left,top:rect.top,width:rect.width,height:rect.height});
zw.rect=rect;
return zw;
}function updateDetailSize(img){var imageObj=new Image();
imageObj.src=img.attr("src");
if(imageObj.width>0&&imageObj.height>0){zw.detailSize=[imageObj.width,imageObj.height];
return;
}else{if(options.detailImageSize){zw.detailSize=options.detailImageSize;
return;
}}var codes=parseMediaServerCodes(imageObj.src);
var aspectRatio=navImageRect[2]/navImageRect[3];
if(codes["SS"]||codes["AA"]){var size=codes["SS"]||codes["AA"];
zw.detailSize=[size,size];
}else{if(codes["SX"]){zw.detailSize=[codes["SX"],Math.round(codes["SX"]/aspectRatio)];
}else{if(codes["SY"]){zw.detailSize=[Math.round(codes["SY"]*aspectRatio),codes["SY"]];
}else{if(codes["SL"]){if(aspectRatio>=1){zw.detailSize=[codes["SL"],Math.round(codes["SL"]/aspectRatio)];
}else{zw.detailSize=[Math.round(codes["SL"]*aspectRatio),codes["SL"]];
}}else{zw.detailSize=[0,0];
imageObj.onload=function(){zw.detailSize=[imageObj.width,imageObj.height];
updateDetailPosition();
};
}}}}}zw.updateImage=function(src){var img=$("<img id='detailImg' src='"+src+"'/>").css("position","absolute");
zw.detailImage&&zw.detailImage.remove();
cropWindow.append(img);
$(document).trigger("updated.magnifier");
zw.detailImage=img;
updateDetailSize(zw.detailImage);
};
zw.refit=function(){fit();
updateDetailSize(zw.detailImage);
return zw;
};
zw.show=function(){cropWindow.show();
return zw;
};
zw.hide=function(){cropWindow.hide();
return zw;
};
zw.destroy=function(){cropWindow.remove();
return zw;
};
zw.updateImage(currentDetailImageUrl);
fit();
cropWindow.appendTo(document.body);
};
function updateDetailPosition(){var pos=lens&&lens.updatePosition();
if(pos&&zoomWindow.detailSize){var range=[zoomWindow.detailSize[0]-zoomWindow.rect.width,zoomWindow.detailSize[1]-zoomWindow.rect.height];
zoomWindow.detailImage.get(0).style.left=-(pos[0]*range[0])+"px";
zoomWindow.detailImage.get(0).style.top=-(pos[1]*range[1])+"px";
}}function locateCursor(e){var touch=hoverZoomIpad?(e.originalEvent.touches[0]||e.originalEvent.changedTouches[0]):"";
cursorAt=hoverZoomIpad?[touch.pageX,touch.pageY]:[e.pageX,e.pageY];
}function onMouseMove(e){if(hoverZoomIpad){e.preventDefault();
}locateCursor(e);
var offset=lens?lens.offset:navImage.offsetParent().offset();
if(cursorAt[0]<navImageRect[0]+offset.left||cursorAt[1]<navImageRect[1]+offset.top||cursorAt[0]>=navImageRect[0]+navImageRect[2]+offset.left||cursorAt[1]>=navImageRect[1]+navImageRect[3]+offset.top){disengage();
}updateDetailPosition();
}function hideSelects(){var selects=$(options.locationElement).find("select:visible");
if(isIE6){hiddenSelects=selects.hide();
}else{$("select").each(function(){$(this).blur();
});
}}function showSelects(){hiddenSelects&&hiddenSelects.show();
}function disengage(){if(!engaged){return;
}if($.browser.msie){$("#main-image-widget .holder.video").show();
}showSelects();
zoomWindow&&zoomWindow.hide();
if(lens){lens.destroy();
lens=null;
}engaged=false;
if(hoverZoomIpad){navImage.unbind("touchmove.magnifier touchstart.magnifier touchend.magnifier");
$(document).trigger("disengaged.magnifier");
}else{$(document).unbind("mousemove.magnifier").trigger("disengaged.magnifier");
}bindEvents();
}function engage(e){if(engaged||magnifierSuppressed){return;
}if(document.body){$(document.body).trigger("click");
}if(options.logMetrics){if(hoverOnLoad==0){var hoverEngageTime=new Date();
var timeDiff=hoverEngageTime-window.ue.t0;
$.imageBlock.logger.logKeyValuePair("hoverTime",timeDiff);
hoverOnLoad=1;
}if(!urlsLogged[currentDetailImageUrl]){$.imageBlock.logger.logHit("hoverMain");
urlsLogged[currentDetailImageUrl]=1;
}}navImageRect=[navImage.position().left,navImage.position().top,navImage.width(),navImage.height()];
if($.browser.msie){$("#main-image-widget .holder.video").hide();
}if(currentDetailImageUrl){if($.browser.msie&&!$.isReady){$("#main-image-widget .holder.video").show();
return;
}hideSelects();
locateCursor(e);
if(zoomWindow){zoomWindow.refit().show();
}else{zoomWindow=new ZoomWindow();
}lens=lens||new Lens();
updateDetailPosition();
}engaged=true;
if(hoverZoomIpad){navImage.unbind("touchstart.magnifier touchmove.magnifier").bind("touchmove.magnifier",onMouseMove).bind("touchend.magnifier",disengage);
$(document).trigger("engaged.magnifier");
}else{navImage.unbind("mousemove.magnifier");
$(document).trigger("engaged.magnifier").bind("mousemove.magnifier",onMouseMove);
}}function unBindEvents(){navImage.unbind("touchstart touchstart.magnifier touchmove.magnifier mousemove.magnifier");
$(document).unbind("mousemove.magnifier");
}function bindEvents(){if(options.useHoverZoom){if(hoverZoomIpad){navImage.bind("touchstart.magnifier touchmove.magnifier",engage);
}else{navImage.bind("mousemove.magnifier",engage);
}}}navImage.preload=function(urls){var urlArray=$.makeArray(urls);
var length=urlArray.length;
for(var i=0;
i<length;
i++){if(urlArray[i] instanceof Array){navImage.preload(urlArray[i]);
}else{if(typeof urlArray[i]=="string"&&urlArray[i]&&!preloaded[urlArray[i]]){preloaded[urlArray[i]]=new Image();
preloaded[urlArray[i]].src=urlArray[i];
}}}};
navImage.changeImage=function(navImageUrl,detailImageUrl){if(engaged){disengage();
}currentDetailImageUrl=detailImageUrl;
navImage.attr("src",navImageUrl);
if($.browser.msie){navImage.get(0).className=navImage.get(0).className;
}navImage.preload(navImageUrl);
navImageRect=[navImage.position().left,navImage.position().top,navImage.width(),navImage.height()];
if(detailImageUrl){if(options.preload=="immediately"){navImage.preload(detailImageUrl,true);
}else{$(window).ready(function(){navImage.preload(detailImageUrl);
});
}if(zoomWindow){zoomWindow.updateImage(detailImageUrl);
}else{navImage.attr("data-old-hires",detailImageUrl);
}}};
navImage.destroy=function(){unBindEvents();
lens&&lens.destroy();
lens=null;
zoomWindow&&zoomWindow.destroy();
zoomWindow=null;
};
navImage.detailImage=function(){return zoomWindow.detailImage;
};
navImage.suppressMagnifier=function(suppress){magnifierSuppressed=suppress;
};
navImage.isEngaged=function(){return engaged;
};
navImage.engageMagnifier=engage;
navImage.disengageMagnifier=disengage;
navImage[0].complete?bindEvents():navImage.one("load",bindEvents);
navImage.preload(this.attr("src"));
if(options.preload){var url=options.detailImageUrl;
var preloadMagnifier=function(){navImage.preload(url,true);
Lens.preload();
};
var eventNames=options.preload;
if(eventNames.constructor!=Array){eventNames=[eventNames];
}for(var i=0;
i<eventNames.length;
i++){if(eventNames[i]=="immediately"){preloadMagnifier();
}else{if($(window)[eventNames[i]]){$(window)[eventNames[i]](preloadMagnifier);
}else{$(window).bind(eventNames[i],preloadMagnifier);
}}}}return navImage;
};
});
var swfobject=function(){var D="undefined",r="object",S="Shockwave Flash",W="ShockwaveFlash.ShockwaveFlash",q="application/x-shockwave-flash",R="SWFObjectExprInst",x="onreadystatechange",O=window,j=document,t=navigator,T=false,U=[h],o=[],N=[],I=[],l,Q,E,B,J=false,a=false,n,G,m=true,M=function(){var aa=typeof j.getElementById!=D&&typeof j.getElementsByTagName!=D&&typeof j.createElement!=D,ah=t.userAgent.toLowerCase(),Y=t.platform.toLowerCase(),ae=Y?/win/.test(Y):/win/.test(ah),ac=Y?/mac/.test(Y):/mac/.test(ah),af=/webkit/.test(ah)?parseFloat(ah.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false,X=!+"\v1",ag=[0,0,0],ab=null;
if(typeof t.plugins!=D&&typeof t.plugins[S]==r){ab=t.plugins[S].description;
if(ab&&!(typeof t.mimeTypes!=D&&t.mimeTypes[q]&&!t.mimeTypes[q].enabledPlugin)){T=true;
X=false;
ab=ab.replace(/^.*\s+(\S+\s+\S+$)/,"$1");
ag[0]=parseInt(ab.replace(/^(.*)\..*$/,"$1"),10);
ag[1]=parseInt(ab.replace(/^.*\.(.*)\s.*$/,"$1"),10);
ag[2]=/[a-zA-Z]/.test(ab)?parseInt(ab.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0;
}}else{if(typeof O.ActiveXObject!=D){try{var ad=new ActiveXObject(W);
if(ad){ab=ad.GetVariable("$version");
if(ab){X=true;
ab=ab.split(" ")[1].split(",");
ag=[parseInt(ab[0],10),parseInt(ab[1],10),parseInt(ab[2],10)];
}}}catch(Z){}}}return{w3:aa,pv:ag,wk:af,ie:X,win:ae,mac:ac};
}(),k=function(){if(!M.w3){return;
}if((typeof j.readyState!=D&&j.readyState=="complete")||(typeof j.readyState==D&&(j.getElementsByTagName("body")[0]||j.body))){f();
}if(!J){if(typeof j.addEventListener!=D){j.addEventListener("DOMContentLoaded",f,false);
}if(M.ie&&M.win){j.attachEvent(x,function(){if(j.readyState=="complete"){j.detachEvent(x,arguments.callee);
f();
}});
if(O==top){(function(){if(J){return;
}try{j.documentElement.doScroll("left");
}catch(X){setTimeout(arguments.callee,0);
return;
}f();
})();
}}if(M.wk){(function(){if(J){return;
}if(!/loaded|complete/.test(j.readyState)){setTimeout(arguments.callee,0);
return;
}f();
})();
}s(f);
}}();
function f(){if(J){return;
}try{var Z=j.getElementsByTagName("body")[0].appendChild(C("span"));
Z.parentNode.removeChild(Z);
}catch(aa){return;
}J=true;
var X=U.length;
for(var Y=0;
Y<X;
Y++){U[Y]();
}}function K(X){if(J){X();
}else{U[U.length]=X;
}}function s(Y){if(typeof O.addEventListener!=D){O.addEventListener("load",Y,false);
}else{if(typeof j.addEventListener!=D){j.addEventListener("load",Y,false);
}else{if(typeof O.attachEvent!=D){i(O,"onload",Y);
}else{if(typeof O.onload=="function"){var X=O.onload;
O.onload=function(){X();
Y();
};
}else{O.onload=Y;
}}}}}function h(){if(T){V();
}else{H();
}}function V(){var X=j.getElementsByTagName("body")[0];
var aa=C(r);
aa.setAttribute("type",q);
var Z=X.appendChild(aa);
if(Z){var Y=0;
(function(){if(typeof Z.GetVariable!=D){var ab=Z.GetVariable("$version");
if(ab){ab=ab.split(" ")[1].split(",");
M.pv=[parseInt(ab[0],10),parseInt(ab[1],10),parseInt(ab[2],10)];
}}else{if(Y<10){Y++;
setTimeout(arguments.callee,10);
return;
}}X.removeChild(aa);
Z=null;
H();
})();
}else{H();
}}function H(){var ag=o.length;
if(ag>0){for(var af=0;
af<ag;
af++){var Y=o[af].id;
var ab=o[af].callbackFn;
var aa={success:false,id:Y};
if(M.pv[0]>0){var ae=c(Y);
if(ae){if(F(o[af].swfVersion)&&!(M.wk&&M.wk<312)){w(Y,true);
if(ab){aa.success=true;
aa.ref=z(Y);
ab(aa);
}}else{if(o[af].expressInstall&&A()){var ai={};
ai.data=o[af].expressInstall;
ai.width=ae.getAttribute("width")||"0";
ai.height=ae.getAttribute("height")||"0";
if(ae.getAttribute("class")){ai.styleclass=ae.getAttribute("class");
}if(ae.getAttribute("align")){ai.align=ae.getAttribute("align");
}var ah={};
var X=ae.getElementsByTagName("param");
var ac=X.length;
for(var ad=0;
ad<ac;
ad++){if(X[ad].getAttribute("name").toLowerCase()!="movie"){ah[X[ad].getAttribute("name")]=X[ad].getAttribute("value");
}}P(ai,ah,Y,ab);
}else{p(ae);
if(ab){ab(aa);
}}}}}else{w(Y,true);
if(ab){var Z=z(Y);
if(Z&&typeof Z.SetVariable!=D){aa.success=true;
aa.ref=Z;
}ab(aa);
}}}}}function z(aa){var X=null;
var Y=c(aa);
if(Y&&Y.nodeName=="OBJECT"){if(typeof Y.SetVariable!=D){X=Y;
}else{var Z=Y.getElementsByTagName(r)[0];
if(Z){X=Z;
}}}return X;
}function A(){return !a&&F("6.0.65")&&(M.win||M.mac)&&!(M.wk&&M.wk<312);
}function P(aa,ab,X,Z){a=true;
E=Z||null;
B={success:false,id:X};
var ae=c(X);
if(ae){if(ae.nodeName=="OBJECT"){l=g(ae);
Q=null;
}else{l=ae;
Q=X;
}aa.id=R;
if(typeof aa.width==D||(!/%$/.test(aa.width)&&parseInt(aa.width,10)<310)){aa.width="310";
}if(typeof aa.height==D||(!/%$/.test(aa.height)&&parseInt(aa.height,10)<137)){aa.height="137";
}j.title=j.title.slice(0,47)+" - Flash Player Installation";
var ad=M.ie&&M.win?"ActiveX":"PlugIn",ac="MMredirectURL="+O.location.toString().replace(/&/g,"%26")+"&MMplayerType="+ad+"&MMdoctitle="+j.title;
if(typeof ab.flashvars!=D){ab.flashvars+="&"+ac;
}else{ab.flashvars=ac;
}if(M.ie&&M.win&&ae.readyState!=4){var Y=C("div");
X+="SWFObjectNew";
Y.setAttribute("id",X);
ae.parentNode.insertBefore(Y,ae);
ae.style.display="none";
(function(){if(ae.readyState==4){ae.parentNode.removeChild(ae);
}else{setTimeout(arguments.callee,10);
}})();
}u(aa,ab,X);
}}function p(Y){if(M.ie&&M.win&&Y.readyState!=4){var X=C("div");
Y.parentNode.insertBefore(X,Y);
X.parentNode.replaceChild(g(Y),X);
Y.style.display="none";
(function(){if(Y.readyState==4){Y.parentNode.removeChild(Y);
}else{setTimeout(arguments.callee,10);
}})();
}else{Y.parentNode.replaceChild(g(Y),Y);
}}function g(ab){var aa=C("div");
if(M.win&&M.ie){aa.innerHTML=ab.innerHTML;
}else{var Y=ab.getElementsByTagName(r)[0];
if(Y){var ad=Y.childNodes;
if(ad){var X=ad.length;
for(var Z=0;
Z<X;
Z++){if(!(ad[Z].nodeType==1&&ad[Z].nodeName=="PARAM")&&!(ad[Z].nodeType==8)){aa.appendChild(ad[Z].cloneNode(true));
}}}}}return aa;
}function u(ai,ag,Y){var X,aa=c(Y);
if(M.wk&&M.wk<312){return X;
}if(aa){if(typeof ai.id==D){ai.id=Y;
}if(M.ie&&M.win){var ah="";
for(var ae in ai){if(ai[ae]!=Object.prototype[ae]){if(ae.toLowerCase()=="data"){ag.movie=ai[ae];
}else{if(ae.toLowerCase()=="styleclass"){ah+=' class="'+ai[ae]+'"';
}else{if(ae.toLowerCase()!="classid"){ah+=" "+ae+'="'+ai[ae]+'"';
}}}}}var af="";
for(var ad in ag){if(ag[ad]!=Object.prototype[ad]){af+='<param name="'+ad+'" value="'+ag[ad]+'" />';
}}aa.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+ah+">"+af+"</object>";
N[N.length]=ai.id;
X=c(ai.id);
}else{var Z=C(r);
Z.setAttribute("type",q);
for(var ac in ai){if(ai[ac]!=Object.prototype[ac]){if(ac.toLowerCase()=="styleclass"){Z.setAttribute("class",ai[ac]);
}else{if(ac.toLowerCase()!="classid"){Z.setAttribute(ac,ai[ac]);
}}}}for(var ab in ag){if(ag[ab]!=Object.prototype[ab]&&ab.toLowerCase()!="movie"){e(Z,ab,ag[ab]);
}}aa.parentNode.replaceChild(Z,aa);
X=Z;
}}return X;
}function e(Z,X,Y){var aa=C("param");
aa.setAttribute("name",X);
aa.setAttribute("value",Y);
Z.appendChild(aa);
}function y(Y){var X=c(Y);
if(X&&X.nodeName=="OBJECT"){if(M.ie&&M.win){X.style.display="none";
(function(){if(X.readyState==4){b(Y);
}else{setTimeout(arguments.callee,10);
}})();
}else{X.parentNode.removeChild(X);
}}}function b(Z){var Y=c(Z);
if(Y){for(var X in Y){if(typeof Y[X]=="function"){Y[X]=null;
}}Y.parentNode.removeChild(Y);
}}function c(Z){var X=null;
try{X=j.getElementById(Z);
}catch(Y){}return X;
}function C(X){return j.createElement(X);
}function i(Z,X,Y){Z.attachEvent(X,Y);
I[I.length]=[Z,X,Y];
}function F(Z){var Y=M.pv,X=Z.split(".");
X[0]=parseInt(X[0],10);
X[1]=parseInt(X[1],10)||0;
X[2]=parseInt(X[2],10)||0;
return(Y[0]>X[0]||(Y[0]==X[0]&&Y[1]>X[1])||(Y[0]==X[0]&&Y[1]==X[1]&&Y[2]>=X[2]))?true:false;
}function v(ac,Y,ad,ab){if(M.ie&&M.mac){return;
}var aa=j.getElementsByTagName("head")[0];
if(!aa){return;
}var X=(ad&&typeof ad=="string")?ad:"screen";
if(ab){n=null;
G=null;
}if(!n||G!=X){var Z=C("style");
Z.setAttribute("type","text/css");
Z.setAttribute("media",X);
n=aa.appendChild(Z);
if(M.ie&&M.win&&typeof j.styleSheets!=D&&j.styleSheets.length>0){n=j.styleSheets[j.styleSheets.length-1];
}G=X;
}if(M.ie&&M.win){if(n&&typeof n.addRule==r){n.addRule(ac,Y);
}}else{if(n&&typeof j.createTextNode!=D){n.appendChild(j.createTextNode(ac+" {"+Y+"}"));
}}}function w(Z,X){if(!m){return;
}var Y=X?"visible":"hidden";
if(J&&c(Z)){c(Z).style.visibility=Y;
}else{v("#"+Z,"visibility:"+Y);
}}function L(Y){var Z=/[\\\"<>\.;]/;
var X=Z.exec(Y)!=null;
return X&&typeof encodeURIComponent!=D?encodeURIComponent(Y):Y;
}var d=function(){if(M.ie&&M.win){window.attachEvent("onunload",function(){var ac=I.length;
for(var ab=0;
ab<ac;
ab++){I[ab][0].detachEvent(I[ab][1],I[ab][2]);
}var Z=N.length;
for(var aa=0;
aa<Z;
aa++){y(N[aa]);
}for(var Y in M){M[Y]=null;
}M=null;
for(var X in swfobject){swfobject[X]=null;
}swfobject=null;
});
}}();
return{registerObject:function(ab,X,aa,Z){if(M.w3&&ab&&X){var Y={};
Y.id=ab;
Y.swfVersion=X;
Y.expressInstall=aa;
Y.callbackFn=Z;
o[o.length]=Y;
w(ab,false);
}else{if(Z){Z({success:false,id:ab});
}}},getObjectById:function(X){if(M.w3){return z(X);
}},embedSWF:function(ab,ah,ae,ag,Y,aa,Z,ad,af,ac){var X={success:false,id:ah};
if(M.w3&&!(M.wk&&M.wk<312)&&ab&&ah&&ae&&ag&&Y){w(ah,false);
K(function(){ae+="";
ag+="";
var aj={};
if(af&&typeof af===r){for(var al in af){aj[al]=af[al];
}}aj.data=ab;
aj.width=ae;
aj.height=ag;
var am={};
if(ad&&typeof ad===r){for(var ak in ad){am[ak]=ad[ak];
}}if(Z&&typeof Z===r){for(var ai in Z){if(typeof am.flashvars!=D){am.flashvars+="&"+ai+"="+Z[ai];
}else{am.flashvars=ai+"="+Z[ai];
}}}if(F(Y)){var an=u(aj,am,ah);
if(aj.id==ah){w(ah,true);
}X.success=true;
X.ref=an;
}else{if(aa&&A()){aj.data=aa;
P(aj,am,ah,ac);
return;
}else{w(ah,true);
}}if(ac){ac(X);
}});
}else{if(ac){ac(X);
}}},switchOffAutoHideShow:function(){m=false;
},ua:M,getFlashPlayerVersion:function(){return{major:M.pv[0],minor:M.pv[1],release:M.pv[2]};
},hasFlashPlayerVersion:F,createSWF:function(Z,Y,X){if(M.w3){return u(Z,Y,X);
}else{return undefined;
}},showExpressInstall:function(Z,aa,X,Y){if(M.w3&&A()){P(Z,aa,X,Y);
}},removeSWF:function(X){if(M.w3){y(X);
}},createCSS:function(aa,Z,Y,X){if(M.w3){v(aa,Z,Y,X);
}},addDomLoadEvent:K,addLoadEvent:s,getQueryParamValue:function(aa){var Z=j.location.search||j.location.hash;
if(Z){if(/\?/.test(Z)){Z=Z.split("?")[1];
}if(aa==null){return L(Z);
}var Y=Z.split("&");
for(var X=0;
X<Y.length;
X++){if(Y[X].substring(0,Y[X].indexOf("="))==aa){return L(Y[X].substring((Y[X].indexOf("=")+1)));
}}}return"";
},expressInstallCallback:function(){if(a){var X=c(R);
if(X&&l){X.parentNode.replaceChild(l,X);
if(Q){w(Q,true);
if(M.ie&&M.win){l.style.display="block";
}}if(E){E(B);
}}a=false;
}}};
}();
P.when("A","jQuery","ImageBlockBTF").register("immersiveView",function(A,$,imageBlockData){var isChromelessVideoPlayer;
var ivTitle;
var ivImageSet;
var ivVideoSet;
var ivCurrentVideoSelected;
var ivCurrentImageSelected;
var ivCurrentSelectedColor;
var ivCurrentAltImageIndexSelected=0;
var ivCurrentAltImageIndexType;
var iVData;
var ivUtils;
var ivMediaUrls;
var ivWidthAdjustment=42;
var ivHeightAdjustment=125;
var ivThumbSectionHeightAdjustment=210;
var ivVideoListHeightAdjustment=30;
var ivIsIVOpened=false;
var ivVideoInfoPopover;
var ivImageLoadState={};
var ivSpinnerLength=104;
var ivSpinnerWidth=80;
var ivLeftCol;
var ivIsImageLoading=false;
var ivIsLargeMode=false;
var ivFullImageWidth;
var ivFullImageHeight;
var ivAlwaysIncludeVideo=0;
var ivMaxAlts=0;
var ivIsPlayingVideo=false;
var ivInitialOffset={left:0,top:0};
var ivMaxOffset={};
var ivVideoMarginSet=false;
var ivFullImageLarge;
var ivCursorStart=[0,0];
var DEFAULT_FULL_SCREEN_MOVE_FACTOR=4;
var ivFullScreenMoveFactor=DEFAULT_FULL_SCREEN_MOVE_FACTOR;
var ivPlayerOnIV=new Object();
var ivDpPlayers={mediaIDs:[],playerDivs:[]};
var logger;
function selectThumbnail(){if(ivCurrentImageSelected>=0){$("#ivimage_"+ivCurrentImageSelected).click();
}else{if(ivCurrentVideoSelected>=0){$("#ivvideo_"+ivCurrentVideoSelected).click();
}else{$("#ivimage_0").click();
}}return;
}this.iVController=function(e,data,imageBlockUtils,imageBlockLogger){if(e==null||data==null||imageBlockUtils==null){return;
}if(!ivUtils){ivUtils=imageBlockUtils;
}if(!isIvApplicable(data)){return;
}if(!logger){logger=imageBlockLogger;
}if(shouldInitializeAgain()){initializeIV(e,data);
clearcache();
createImmersiveView();
}else{initializeSelection(e);
$("#iv_media_select").val("all");
$(".iv_thumb_videos").hide();
$(".iv_thumbs").show();
$(".iv_type_video").show();
}$.AmazonPopover.displayPopover(getIVPopoverOptions());
};
var initializeSelection=function(e){var altImageSelectedDataInfo=getAltImageIndexSelected(e);
ivCurrentAltImageIndexSelected=altImageSelectedDataInfo.thumbnailIndex;
ivCurrentAltImageIndexType=altImageSelectedDataInfo.type;
if(ivCurrentAltImageIndexType=="image"){ivCurrentImageSelected=altImageSelectedDataInfo.index;
ivCurrentVideoSelected=-1;
}else{ivCurrentImageSelected=-1;
ivCurrentVideoSelected=altImageSelectedDataInfo.index;
}};
var shouldInitializeAgain=function(){if(!ivCurrentSelectedColor){return true;
}else{if(isTwisterPage()){if(typeof DetailPage!="undefined"&&DetailPage.StateController){var currentSelectedColor=ivUtils.getColorFromState(DetailPage.StateController.getState()["selected_variations"]);
if(currentSelectedColor==ivCurrentSelectedColor){return false;
}}}else{return false;
}}return true;
};
var isTwisterPage=function(){if(typeof isTwisterPage!="undefined"&&isTwisterPage){return true;
}return false;
};
function clearcache(){if(iVData){iVData.remove();
}}var initializeIV=function(e,data){initializeSelection(e);
ivCurrentSelectedColor=getCurrentSelectedColor(data);
ivImageSet=getImages(data.colorImages);
window.ivStrings=data.staticStrings;
ivTitle=data.title;
ivMediaUrls=data.staticImages;
ivAlwaysIncludeVideo=data.alwaysIncludeVideo;
isChromelessVideoPlayer=data.useChromelessVideoPlayer;
ivMaxAlts=data.maxAlts;
if(!isChromelessVideoPlayer){ivVideoSet=buildIVVideos();
}};
function constructLeftColumn(){var imgContainer,vidContainer;
ivLeftCol=$('<div id="iv-first-column" style="float: left; width:'+($(window).width()-ivWidthAdjustment-330)+'px;height:100%; margin-right: 15px;"/>');
imgContainer=$('<div width="100%" id="iv-large-image" style="overflow: hidden; width: 100%; height: '+($(window).height()-ivHeightAdjustment-15)+'px;align:center; position:relative; top:0px; left:0px;"/>');
vidContainer=$('<div width="100%" id="iv-large-video" style="overflow: hidden; width: 100%; height: 100%;align:center; "/>');
if(ivCurrentAltImageIndexType=="image"){vidContainer.css("display","none");
}else{imgContainer.css("display","none");
}ivLeftCol.append(imgContainer);
ivLeftCol.append(vidContainer);
iVData.append(ivLeftCol);
}function constructTitle(rightCol){var style='<style type="text/css">a.iv-title-link:link {text-decoration: none;}a.iv-title-link:visited {text-decoration: none; color: #003399}a.iv-title-link:hover {text-decoration: underline; color: orange;}</style>';
$(style).appendTo("head");
var titleHtml='<div style="text-align: left; margin-top: 10px; font-family: verdana, arial, helvetica, sans-serif; font-size: 14px; font-weight: bold; '+'word-wrap: break-word; width: 235px;" id="iv-prod-title" title="'+ivTitle+'">'+'<a class="ap_custom_close iv-title-link" href="">'+trimWithEllipsis(ivTitle,45)+"</a></div>";
var titleBar=$(titleHtml);
rightCol.append(titleBar);
}function constructVariationColor(rightCol){if(!ivCurrentSelectedColor){return;
}if(typeof DetailPage!="undefined"&&DetailPage.StateController){var varSelectionHtml='<div style="text-align: left;"  id="iv-variation-selection">';
var pageState=DetailPage.StateController.getState();
var labels=pageState["variation_label_order"];
var labelCount=0;
for(var i in labels){var label=labels[i];
var labelValue=pageState["selected_variations"][label];
var labelKey=pageState["variation_display_labels"][label];
if(labelValue){varSelectionHtml+='<div style="padding-top:10px; padding-bottom:3px; font-family: verdana, arial, helvetica, sans-serif; font-size:11px; color:#666">'+labelKey+" : "+labelValue+"</div>";
}}varSelectionHtml+="</div>";
var variationSelection=$(varSelectionHtml);
rightCol.append(variationSelection);
}}function constructMediaSelection(rightCol){var tabHtml='<div style="width:235px; border:1px solid #C9E1F4; background-color:#EAF3FD; padding-top: 5px; padding-bottom: 5px; margin-top:15px; display: none" id="iv-tabbing">';
tabHtml+='<select id="iv_media_select" style="position:relative;left:65px">';
tabHtml+='<option id="all" value="all" selected>'+ivStrings["allMedia"]+"</option>";
tabHtml+='<option id="images" value="images">'+ivStrings["images"]+"</option>";
tabHtml+='<option id="videos" value="videos">'+ivStrings["videos"]+"</option>";
tabHtml+="</select>";
if($.browser.msie){tabHtml+='<span class="swSprite s_boxLeft" style="top: -14px; left: -102px; display: none;"> </span>  <span class="swSprite s_boxRight" style="top: -14px; left: 111px; display: none;"> </span>';
}else{tabHtml+='<span class="swSprite s_boxLeft" style="top: -12px; left: -102px; display: none;"> </span>  <span class="swSprite s_boxRight" style="top: -12px; left: 108px; display: none;"> </span>';
}tabHtml+="</div>";
var mediaSelection=$(tabHtml);
rightCol.append(mediaSelection);
}function constructThumbs(rightCol){var style='<style type="text/css">.iv_thumbs { border:1px solid #C9E1F4;width:235px;height:290px;padding-left:15px;padding-top:15px;padding-bottom:15px; overflow-y:auto; border-top:0px;position:relative; top:0px; left:0px; }.iv_thumb_videos {  border:1px solid #C9E1F4;width:235px;height:230px;padding:0px; overflow-y:auto; border-top:0px; }.iv_thumb_video_outer { float:left; width:100%; padding-top:5px; padding-bottom:5px;cursor:pointer}.iv_thumb_video_outer_hover { background-color: #EAF3FD }.iv_thumb_video { border: 1px solid #ddd;float:left; margin-left:10px;margin-right:10px;cursor:pointer; }.iv_thumb { border: 1px solid #ddd;float:left; margin-right:12px; margin-bottom:20px; cursor:pointer; }.iv_thumb_selected { border: 2px solid #E47911; }.iv_thumb_hover { border: 2px solid #004B91; }.iv_thumb_inner { padding: 1px;float:left; }.iv_thumb_inner_selected { padding: 0px; }.iv_thumb_image { float:left;position:relative;width:50px; height:50px; background-color:#ffffff}.iv_thumb_text { float:left; word-wrap:break-word; width:130px; margin-top:10px; font-family:verdana, arial, helvetica, sans-serif; font-size:11px }.iv_thumb_text_popover { font-family: verdana, arial, helvetica, sans-serif; font-size:11px }.iv_thumb_text_hover { background-color: #EAF3FD }</style>';
$(style).appendTo("head");
var thumbHtml="<div class='iv_thumbs'>";
thumbHtml+="</div>";
thumbHtml+="<div class='iv_thumb_videos' style='display: none; height: 63px;'>";
thumbHtml+="</div>";
var thumbs=$(thumbHtml);
rightCol.append(thumbs);
prefetchResources();
}function prefetchResources(){$("<img>").attr("src",""+ivMediaUrls["arrow"]+"");
$("<img>").attr("src",""+ivMediaUrls["zoomIn"]+"");
$("<img>").attr("src",""+ivMediaUrls["zoomOut"]+"");
}function constructRightColumn(){var rightCol=$('<div style="float: left; width: 235px;" id="iv-sec-column"></div>');
constructTitle(rightCol);
constructVariationColor(rightCol);
constructMediaSelection(rightCol);
constructThumbs(rightCol);
iVData.append(rightCol);
}function addHandlers(){$("#addIV-Main").click(function(){$("#iv_media_select").css("visibility","visible");
});
$(window).resize(function(){if(ivIsIVOpened){resizeIV();
}});
addThumbHandlers();
}function addThumbHandlers(){$(".iv_thumb").click(function(event){$(".iv_thumb").removeClass("iv_thumb_selected");
$(".iv_thumb").removeClass("iv_thumb_hover");
$(".iv_thumb").find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
$(this).addClass("iv_thumb_selected");
$(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
if($(this).hasClass("iv_type_video")){ivCurrentVideoSelected=$(this).attr("id").split("_")[1];
ivCurrentImageSelected=-1;
playVideo();
}else{ivCurrentImageSelected=$(this).attr("id").split("_")[1];
ivCurrentVideoSelected=-1;
changeMainImage();
}});
$(".iv_thumb_video_outer").click(function(event){$(".iv_thumb_video").removeClass("iv_thumb_selected");
$(".iv_thumb_video").removeClass("iv_thumb_hover");
$(".iv_thumb_video").find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
$(this).find(".iv_thumb_video").addClass("iv_thumb_selected");
$(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
ivCurrentVideoSelected=$(this).attr("id").split("_")[1];
ivCurrentImageSelected=-1;
playVideo();
});
$(".iv_thumb").mouseover(function(event){if(ivVideoInfoPopover){ivVideoInfoPopover.close();
}if(!$(this).hasClass("iv_thumb_selected")){$(this).addClass("iv_thumb_hover");
$(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
}if($(this).hasClass("iv_type_video")){var videos=ivVideoSet[0].videos;
var videoID=$(this).attr("id").split("_")[1];
var videoContent="<span class='iv_thumb_text_popover'><b>"+videos.titles[videoID]+"</b><br>"+videos.durations[videoID]+"</span>";
var leftOffset=(($(this).offset().left-$(".iv_thumbs").offset().left)<=30)?-27:-50;
var topOffset=-11;
if($.browser.msie&&parseInt($.browser.version)==6){topOffset=-16;
}ivVideoInfoPopover=$.AmazonPopover.displayPopover({literalContent:videoContent,width:180,location:["top"],locationElement:this,locationAlign:"middle",locationOffset:[leftOffset,topOffset],zIndex:1000,hoverShowDelay:300,hoverHideDelay:300,showCloseButton:false,attached:true,modal:false});
if($.browser.msie&&parseInt($.browser.version)==6){ivVideoInfoPopover.find(".ap_footer").find(".ap_middle").css({position:"relative",height:"30px",width:"112px",top:"-2px",background:"url("+ivMediaUrls["arrow"]+") -343px -40px"});
}else{ivVideoInfoPopover.find(".ap_footer").find(".ap_middle").css({position:"relative",height:"30px",width:"112px",top:"-3px",background:"url("+ivMediaUrls["arrow"]+") -343px -43px"});
}}});
$(".iv_thumb_video_outer").mouseover(function(event){$(this).addClass("iv_thumb_video_outer_hover");
$(this).find(".iv_thumb_text").addClass("iv_thumb_text_hover");
if(!$(this).find(".iv_thumb_video").hasClass("iv_thumb_selected")){$(this).find(".iv_thumb_video").addClass("iv_thumb_hover");
$(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
}});
$(".iv_thumb").mouseout(function(event){if(!$(this).hasClass("iv_thumb_selected")){$(this).removeClass("iv_thumb_hover");
$(this).find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
}if(ivVideoInfoPopover){ivVideoInfoPopover.close();
}});
$(".iv_thumb_video_outer").mouseout(function(event){$(this).removeClass("iv_thumb_video_outer_hover");
$(this).find(".iv_thumb_text").removeClass("iv_thumb_text_hover");
if(!$(this).find(".iv_thumb_video").hasClass("iv_thumb_selected")){$(this).find(".iv_thumb_video").removeClass("iv_thumb_hover");
$(this).find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
}});
$("#ap_container").keydown(function(event){if(event.keyCode==37||event.keyCode==38||event.keyCode==39||event.keyCode==40||event.keyCode==33||event.keyCode==34){return false;
}});
}function changeMainImage(){if(ivVideoSet&&AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId]){try{AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId].pause();
}catch(e){logger.logKeyValuePair("AmznVideoPlayer.pause","exception "+e.message+" user agent "+navigator.userAgent);
}}if(ivVideoSet){AmznVideoPlayer.hideAll();
}$("#iv-large-video").css("display","none");
$("#iv-large-image").css("display","block");
var currentDetailImageUrl="";
var currentDetailImageUrl;
if(ivImageSet&&ivImageSet[ivCurrentSelectedColor]&&ivImageSet[ivCurrentSelectedColor].images){currentDetailImageUrl=ivImageSet[ivCurrentSelectedColor].images.zoomImages[ivCurrentImageSelected];
}if(!currentDetailImageUrl){return;
}if(iVData.find(".fullScreen")){iVData.find(".fullScreen").remove();
}ivFullImageLarge="<img src='"+currentDetailImageUrl+"'class='fullScreen'/>";
var ivFullImageFit=$("<img>").attr("src",currentDetailImageUrl);
ivFullImageFit.addClass("fullScreen");
var largeImage=$("#iv-large-image");
largeImage.animate({opacity:0.4},200,function(){ivFullImageFit.load(function(){loadImage();
});
$(ivFullImageLarge).load(function(){loadImage();
});
if(!ivImageLoadState[ivFullImageFit.attr("src")]){ivIsImageLoading=true;
largeImage.empty();
var top=(ivLeftCol.height()-ivSpinnerLength)/2;
var left=(ivLeftCol.width()-ivSpinnerWidth)/2;
$("#iv-large-image").append("<img src='"+ivMediaUrls["spinner"]+"' style='position:relative;top:"+top+"px;left:"+left+"px;' />");
}else{loadImage();
}});
ivFullImageFit.load(function(){ivImageLoadState[ivFullImageFit.attr("src")]=1;
prefetchImages();
});
$(ivFullImageLarge).load(function(){ivImageLoadState[ivFullImageFit.attr("src")]=1;
prefetchImages();
});
function loadImage(){ivIsImageLoading=false;
largeImage.css("visibility","hidden");
largeImage.empty();
largeImage.animate({opacity:1},200);
largeImage.append(ivFullImageFit);
imageFit();
ivIsPlayingVideo=false;
ivImageLoadState[ivFullImageFit.attr("src")]=1;
}}function imageFit(){ivIsLargeMode=false;
var ivLargeImage=$("#iv-large-image");
var ww=ivLargeImage.width();
var wh=ivLargeImage.height();
var fullImageFit=$("#iv-large-image").find(".fullScreen");
fullImageFit.removeAttr("style");
ivFullImageWidth=fullImageFit.width();
var maxImgaeSize=ivFullImageWidth;
ivFullImageHeight=fullImageFit.height();
maxImgaeSize=maxImgaeSize>ivFullImageHeight?maxImgaeSize:ivFullImageHeight;
if(fullImageFit.length>0){if(fullImageFit[0].naturalWidth){ivFullImageWidth=fullImageFit[0].naturalWidth;
maxImgaeSize=maxImgaeSize>ivFullImageWidth?maxImgaeSize:ivFullImageWidth;
}if(fullImageFit[0].naturalHeight){ivFullImageHeight=fullImageFit[0].naturalHeight;
maxImgaeSize=maxImgaeSize>ivFullImageHeight?maxImgaeSize:ivFullImageHeight;
}}ivLeftCol.css({"cursor":"auto"});
if(maxImgaeSize>=1000){if($.browser.mozilla){ivLeftCol.css({"cursor":"-moz-zoom-in"});
}else{ivLeftCol.css({"cursor":"url('"+ivMediaUrls["zoomIn"]+"'), auto"});
}}ivFullImageWidth=ivFullImageWidth==0?1:ivFullImageWidth;
ivFullImageHeight=ivFullImageHeight==0?1:ivFullImageHeight;
var scale=Math.min(ww/ivFullImageWidth,wh/ivFullImageHeight);
var fitHeight=ivFullImageHeight*scale;
var fitWidth=ivFullImageWidth*scale;
var imgHeight;
if(fitHeight<ivFullImageHeight){imgHeight=fitHeight-20;
}else{imgHeight=ivFullImageHeight;
}fullImageFit.css("height",imgHeight);
fullImageFit.css("width",Math.min(fitWidth,ivFullImageWidth));
var left=((ww-fullImageFit.width())/2);
var top=((wh-fullImageFit.height())/2);
fullImageFit.css("margin-top",top);
fullImageFit.css("margin-left",left);
$("#iv-large-image").css("visibility","visible");
}function prefetchImages(){for(var i=-3;
i<=3;
i++){var id=parseInt(ivCurrentImageSelected)+i;
if(id<0){continue;
}var imgURL=(ivImageSet&&ivImageSet[ivCurrentImageSelected])?ivImageSet[ivCurrentImageSelected].images.zoomImages[id]:"";
if(imgURL&&ivImageLoadState[imgURL]==undefined){var imgObject=$("<img>").attr("src",imgURL);
imgObject.load(function(){ivImageLoadState[$(this).attr("src")]=1;
});
}else{if(!imgURL){break;
}}}}function resizeIV(){var height=$(window).height()-ivHeightAdjustment;
var width=($(window).width()-ivWidthAdjustment);
if(height>230){$("#IV-Main").css({"height":(height)+"px"});
$("#iv-large-image").css({"height":(height-15)+"px"});
var thumbsSecHeight=(height-ivThumbSectionHeightAdjustment);
$(".iv_thumbs").css({"height":(thumbsSecHeight)+"px"});
$(".iv_thumb_videos").css({"height":(thumbsSecHeight+ivVideoListHeightAdjustment)+"px"});
}if(width>500){$("#IV-Main").parents(".ap_popover").css({"width":(width)+"px"});
$("#iv-first-column").css({"width":(width-330)+"px"});
}if(ivVideoSet&&ivCurrentVideoSelected&&ivVideoSet[0]&&ivVideoSet[0].videos.mediaIDs&&ivVideoSet[0].videos.mediaIDs[ivCurrentVideoSelected]){var currMediaID=ivVideoSet[0].videos.mediaIDs[ivCurrentVideoSelected];
if(AmznVideoPlayer.players[currMediaID]){AmznVideoPlayer.players[currMediaID].resizeVideo(ivLeftCol.width(),ivLeftCol.height());
AmznVideoPlayer.players[currMediaID].showFlash();
}}else{imageFit();
}}var createImmersiveView=function(){iVData=$('<div style="display:none;height:'+($(window).height()-ivHeightAdjustment)+'px; width:100%; padding: 0px 15px 15px 15px;" id="IV-Main"></div>');
constructLeftColumn();
constructRightColumn();
iVData.append('<div style="clear:both"/>');
$("#imageBlock_feature_div").before(iVData);
iVData.find("#iv-large-image").click(function(e){if(ivIsPlayingVideo){return;
}if(ivIsImageLoading){return;
}if(ivIsLargeMode){imageFit();
}else{ivInitialOffset=getFullScreenOffset(ivInitialOffset);
if((ivFullImageWidth>=1000)||(ivFullImageHeight>=1000)){var largeImage=ivLeftCol.find("#iv-large-image");
largeImage.empty().append(ivFullImageLarge);
iVData.find(".fullScreen").load(function(){largeMode();
positionImage(e);
});
}}});
iVData.find("#iv-first-column").mousemove(function(e){if(ivIsLargeMode){positionImage(e);
}});
prefetchResources();
populateMediaSelection();
populateRightColumn();
addHandlers();
resizeIV();
};
function positionImage(e){var newLeft=ivInitialOffset.left-(e.pageX-ivCursorStart[0])*ivFullScreenMoveFactor;
var newTop=ivInitialOffset.top-(e.pageY-ivCursorStart[1])*ivFullScreenMoveFactor;
var newOffset=getFullScreenOffset({left:newLeft,top:newTop});
iVData.find(".fullScreen").css({"left":newOffset.left,"top":newOffset.top});
}function largeMode(){if(!((ivFullImageWidth>=1000)||(ivFullImageHeight>=1000))){return;
}if($.browser.mozilla){ivLeftCol.css({"cursor":"-moz-zoom-out"});
}else{ivLeftCol.css({"cursor":"url('"+ivMediaUrls["zoomOut"]+"'), auto"});
}ivIsLargeMode=true;
var largeImage=ivLeftCol.find("#iv-large-image");
setupMaxOffset();
var centerHeight=ivLeftCol.height()/2;
var centerWidth=ivLeftCol.width()/2;
ivCursorStart=[largeImage.offset().left+centerWidth,largeImage.offset().top+centerHeight];
ivInitialOffset.top=centerHeight-ivFullImageHeight/2;
ivInitialOffset.left=centerWidth-ivFullImageWidth/2;
ivLeftCol.find(".fullScreen").css({position:"relative",left:ivInitialOffset.left,top:ivInitialOffset.top});
ivFullScreenMoveFactor=Math.max(ivFullImageHeight/ivLeftCol.height(),ivFullImageWidth/ivLeftCol.width());
ivFullScreenMoveFactor=Math.max(ivFullScreenMoveFactor,DEFAULT_FULL_SCREEN_MOVE_FACTOR);
}function setupMaxOffset(){var fullImageFit=iVData.find(".fullScreen");
ivFullImageWidth=fullImageFit.width();
ivFullImageHeight=fullImageFit.height();
ivMaxOffset.left=ivLeftCol.width()-ivFullImageWidth;
ivMaxOffset.top=ivLeftCol.height()-ivFullImageHeight;
}function getFullScreenOffset(offset){var newOffset=offset;
if(ivMaxOffset.left>0){newOffset.left=ivMaxOffset.left/2;
}else{if(offset.left<ivMaxOffset.left){newOffset.left=ivMaxOffset.left;
}else{if(offset.left>0){newOffset.left=0;
}}}if(ivMaxOffset.top>0){newOffset.top=ivMaxOffset.top/2;
}else{if(offset.top<ivMaxOffset.top){newOffset.top=ivMaxOffset.top;
}else{if(offset.top>0){newOffset.top=0;
}}}return newOffset;
}function populateMediaSelection(){var imageCount=0,videoCount=0;
if(ivImageSet&&ivImageSet[ivCurrentSelectedColor]&&ivImageSet[ivCurrentSelectedColor].images&&ivImageSet[ivCurrentSelectedColor].images.thumbnails){imageCount=ivImageSet[ivCurrentSelectedColor].images.thumbnails.length;
}if(ivVideoSet&&ivVideoSet[0]&&ivVideoSet[0].videos&&ivVideoSet[0].videos.slateImages){videoCount=ivVideoSet[0].videos.slateImages.length;
}var ivThumbs=$(".iv_thumbs");
var ivTabbing=$("#iv-tabbing");
if(imageCount==0||videoCount==0){ivTabbing.hide();
ivThumbs.css({"margin-top":"15px","border-top":"1px solid #C9E1F4"});
return;
}var mediaSelection=$("#iv_media_select");
mediaSelection.find("#all").text(ivStrings["allMedia"]+" ("+(imageCount+videoCount)+")");
mediaSelection.find("#videos").remove();
mediaSelection.find("#images").remove();
mediaSelection.append('<option id="images" value="images">'+ivStrings["images"]+" ("+(imageCount)+")</option>");
mediaSelection.append('<option id="videos" value="videos">'+ivStrings["videos"]+" ("+(videoCount)+")</option>");
ivTabbing.show();
ivThumbs.css({"margin-top":"0px","border-top":"0px"});
mediaSelection.val("all");
addMediaSelectionEvent();
}function addMediaSelectionEvent(){$("#iv_media_select").change(function(){if($(this).val()=="all"){$(".iv_thumb_videos").hide();
$(".iv_thumbs").show();
$(".iv_type_video").show();
if(ivCurrentImageSelected>=0){ivCurrentVideoSelected=-1;
$("#ivimage_"+ivCurrentImageSelected).click();
}else{if(ivCurrentVideoSelected>=0){ivCurrentImageSelected=-1;
$("#ivvideo_"+(ivCurrentVideoSelected)).click();
}}}else{if($(this).val()=="images"){$(".iv_thumb_videos").hide();
$(".iv_thumbs").show();
$(".iv_type_video").hide();
ivCurrentVideoSelected=-1;
if(ivCurrentImageSelected>=0){$("#ivimage_"+ivCurrentImageSelected).click();
}else{ivCurrentImageSelected=0;
$("#ivimage_0").click();
}}else{if($(this).val()=="videos"){$(".iv_thumb_videos").show();
$(".iv_thumbs").hide();
ivCurrentImageSelected=-1;
if(ivCurrentVideoSelected>=0){$("#ivvideolist_"+(ivCurrentVideoSelected)).click();
}else{ivCurrentVideoSelected=0;
$("#ivvideolist_0").click();
}}}}});
}function populateRightColumn(){populateThumbNails();
populateVideoList();
}function populateVideoList(){var videoThumbnails,videoTitles,videoDurations,videoIDs;
if(ivVideoSet&&ivVideoSet[0]){var video=ivVideoSet[0].videos;
videoThumbnails=video.slateImages;
videoTitles=video.titles;
videoDurations=video.durations;
videoIDs=video.mediaIDs;
var thumbHtml="";
if(videoThumbnails){var length=videoThumbnails.length;
for(var i=0;
i<length;
i++){thumbHtml+="<div class='iv_thumb_video_outer' id='ivvideolist_"+i+"'>";
thumbHtml+="<div class='iv_thumb_video'>";
thumbHtml+="<div class='iv_thumb_inner'>";
thumbHtml+="<div class='iv_thumb_image' style=\"background:url("+(videoThumbnails[i])+') center no-repeat">';
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="<div class='iv_thumb_text'><b>"+videoTitles[i]+"</b><br>"+videoDurations[i]+"<div style='clear:both'></div></div>";
thumbHtml+="</div>";
}}var ivVideoList=$(".iv_thumb_videos").html(thumbHtml);
}}function populateThumbNails(){var thumbnails;
var videoThumbnails,videoTitles,videoDurations,videoIDs;
if(ivImageSet&&ivImageSet[ivCurrentSelectedColor]){thumbnails=ivImageSet[ivCurrentSelectedColor].images.thumbnails;
}if(ivVideoSet&&ivVideoSet[0]){videoThumbnails=ivVideoSet[0].videos;
}var thumbHtml="";
var thumbnailNumPerRow=3;
var thumbnailIndex=0;
var thumbnailCount=(thumbnails)?thumbnails.length:0;
thumbnailCount+=(videoThumbnails)?videoThumbnails.length:0;
if(thumbnails){var length=thumbnails.length;
for(var i=0;
i<length;
i++){if(thumbnailIndex%thumbnailNumPerRow==0){thumbHtml+="<div style='height:75px;'>";
}thumbHtml+="<div class='iv_thumb' id='ivimage_"+i+"'>";
thumbHtml+="<div class='iv_thumb_inner'>";
thumbHtml+="<div class='iv_thumb_image' style=\"background:url("+getResizedThumbnailURL(thumbnails[i])+') center no-repeat">';
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="</div>";
if((thumbnailIndex+1)%thumbnailNumPerRow==0||thumbnailIndex==thumbnailCount-1){thumbHtml+="</div>";
}thumbnailIndex++;
}}if(videoThumbnails){var length=videoThumbnails.slateImages.length;
for(var i=0;
i<length;
i++){if(thumbnailIndex%thumbnailNumPerRow==0){thumbHtml+="<div style='height:75px;'>";
}thumbHtml+="<div class='iv_thumb iv_type_video' id='ivvideo_"+i+"'>";
thumbHtml+="<div class='iv_thumb_inner'>";
thumbHtml+="<div class='iv_thumb_image' style=\"background:url("+(videoThumbnails.slateImages[i])+') center no-repeat">';
thumbHtml+="</div>";
thumbHtml+="<div id='data_ivvideo_"+i+"' value='"+videoThumbnails.mediaIDs[i]+"' />";
thumbHtml+="</div>";
thumbHtml+="</div>";
if((thumbnailIndex+1)%thumbnailNumPerRow==0||thumbnailIndex==thumbnailCount-1){thumbHtml+="</div>";
}thumbnailIndex++;
}}$(".iv_thumbs").html(thumbHtml);
}function playVideo(){if(!ivVideoSet||!ivVideoSet[0]||!ivCurrentVideoSelected){return;
}var mediaID=ivVideoSet[0].videos.mediaIDs[ivCurrentVideoSelected];
if(!mediaID){return;
}$("#iv-large-image").css("display","none");
$("#iv-large-video").css("display","block");
$("#iv-large-image").empty();
var lastVideo=AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId];
var holderID="holder"+mediaID;
var mediaElement=$("#"+holderID);
if(mediaElement.length>0){if($(".imgTagWrapper").find("#"+holderID).length>0){var cloneMediaElement=mediaElement.clone();
mediaElement.remove();
$("#iv-large-video").append(cloneMediaElement);
}}else{if(!$("#"+holderID).length){var placeHolder=$("<div style='position:absolute' id='holder"+mediaID+"'></div>");
$("#iv-large-video").append($(placeHolder));
}}if(!AmznVideoPlayer.players[mediaID]||(!$("#flashDiv"+mediaID).children().length>0)){ivPlayerOnIV[mediaID]=true;
if(!window.players){window.players=new Array();
}var mediaObject={mediaObjectId:mediaID,slateImageUrl:ivVideoSet[0].videos.slateImages[ivCurrentVideoSelected]};
window.players[ivCurrentVideoSelected]=new AmznVideoPlayer(mediaObject,holderID,ivLeftCol.width(),ivLeftCol.height());
}if(lastVideo){try{lastVideo.stop();
}catch(e){logger.logKeyValuePair("AmznVideoPlayer.stop","exception "+e.message+" user agent "+navigator.userAgent);
}}AmznVideoPlayer.hideAll();
AmznVideoPlayer.players[mediaID].resizeVideo(ivLeftCol.width(),ivLeftCol.height());
AmznVideoPlayer.players[mediaID].showFlash();
AmznVideoPlayer.players[mediaID].play();
}function getResizedVideoThumbURL(url){url=url.replace(/'/g,"").replace("._SL75_","").replace(/\._(AA|SS)\d+(?!_PImini-player-shuttle-50px,BottomLeft,0,3)_/,"").replace(/\._SX3\d+_SY\d+_CR,0,0,\d+,\d+_/,"");
if(url.search("_SS50_")<0){var index=url.lastIndexOf(".");
url=url.substring(0,index)+"._SS50_PImini-player-shuttle-50px,BottomLeft,0,3_"+url.substring(index);
url=url.replace("_._","._");
}return url;
}function getResizedThumbnailURL(url){url=url.replace(/'/g,"").replace("._SL75_","").replace(/\._(AA|SS)\d+_/,"").replace(/\._SX\d+_SY\d+_CR,0,0,\d+,\d+_/,"");
url=url.replace(/\._(US)\d+_/,"").replace(/\._SR\d+,\d+_/,"");
var index=url.lastIndexOf(".");
url=url.substring(0,index)+"._AA50_"+url.substring(index);
return url;
}var getAltImageIndexSelected=function(e){var data;
if(e.action=="thumb-action"){data=e.data;
}else{if(e.action=="main-image-click"){var selectedThumb=$("altImages,.a-button-selected");
if(selectedThumb!=null&&selectedThumb.parent()!=null&&selectedThumb.parent().data()!=null){data=selectedThumb.parent().data().thumbAction;
}}}if(data==null){data.thubnailIndex=0;
data.type="image";
data.index=0;
}return data;
};
var getImages=function(imageData){var images=new Object();
$.each(imageData,function(index){images[index]={images:{thumbnails:$.map(imageData[index],function(image){return image.thumb;
}),zoomImages:$.map(imageData[index],function(image){return image.hiRes||image.large||image.main[image.main.length-1];
})}};
});
return images;
};
var isArray=function(obj){return Object.prototype.toString.call(obj)==="[object Array]";
};
var buildIVVideos=function(){var ivVideoSet={mediaIDs:[],slateImages:[],titles:[],durations:[]};
var videoSet=ivUtils.getVideos(ivCurrentSelectedColor);
if(!isArray(videoSet)){videoSet=[];
}var length=videoSet.length;
for(var i=0;
i<length;
i++){var videoHash=videoSet[i];
ivVideoSet.mediaIDs[i]=videoHash.mediaObjectId;
ivVideoSet.slateImages[i]=videoHash.ivThumb;
ivVideoSet.titles[i]=videoHash.title;
ivVideoSet.durations[i]=videoHash.duration;
}return[{videos:ivVideoSet}];
};
var isIvApplicable=function(data){var currentSelectedColor=getCurrentSelectedColor(data);
if(data.colorImages&&data.colorImages[currentSelectedColor]&&data.colorImages[currentSelectedColor].length>0&&data.useIV){return true;
}return false;
};
var getCurrentSelectedColor=function(data){var currentSelectedColor=null;
if(typeof DetailPage!="undefined"&&DetailPage.StateController){currentSelectedColor=ivUtils.getColorFromState(DetailPage.StateController.getState()["selected_variations"]);
}currentSelectedColor=currentSelectedColor||data.defaultColor;
return currentSelectedColor;
};
var getIVPopoverOptions=function(){var closeString="close";
var strings=imageBlockData["staticStrings"];
if(strings&&strings["close"]){closeString=strings["close"];
}return{localContent:"#IV-Main",width:($(window).width()-ivWidthAdjustment),location:function(popover,settings){return{left:20,top:28};
},zIndex:999,paddingLeft:0,paddingRight:0,paddingBottom:0,closeText:closeString,modal:true,group:"ImmersiveView",onShow:updateIV,onHide:resetDP};
};
function resetDP(){$("#iv-large-image").empty();
$(document.body).css("overflow","auto");
$("#ap_container").unbind("keydown");
if(ivVideoSet&&AmznVideoPlayer.lastPlayedId){if(AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId]){try{AmznVideoPlayer.players[AmznVideoPlayer.lastPlayedId].stop();
}catch(e){logger.logKeyValuePair("AmznVideoPlayer.stop","exception "+e.message+" user agent "+navigator.userAgent);
}}AmznVideoPlayer.hideAll();
}ivIsIVOpened=false;
if(ivCurrentAltImageIndexType!="image"&&ivCurrentAltImageIndexSelected){$("#altImages").find(".a-button-selected").mouseenter();
}}function updateIV(){ivIsIVOpened=true;
$(document.body).css("opacity","");
var bStyle=document.body.style;
if($.browser.msie&&bStyle&&bStyle.filter==""){bStyle.removeAttribute("filter");
}$("#IV-Main").parents(".ap_popover").css({"top":($("body").scrollTop()+28)+"px"});
selectThumbnail();
resizeIV();
}function clearAllSelections(){$(".iv_thumb").removeClass("iv_thumb_selected");
$(".iv_thumb").removeClass("iv_thumb_hover");
$(".iv_thumb_video").removeClass("iv_thumb_selected");
$(".iv_thumb_video").removeClass("iv_thumb_hover");
}function trimWithEllipsis(str,maxCharacters){str=new String(str);
var trimmedStr=str;
if(str.length>maxCharacters){try{var index=-1;
for(var i=0;
i<str.length;
i++){var c=str.charAt(i);
if(c==" "||c=="."||c=="?"||c==";"||c==","||c==":"){index=i;
}if(i==maxCharacters-4){var trimIndex=(index==-1?i:index);
trimmedStr=str.substring(0,trimIndex);
break;
}}}catch(e){trimmedStr=str.substring(0,maxCharacters-3);
}trimmedStr+="...";
}return trimmedStr;
}return this;
});
P.when("jQuery").register("chromelessVideoPlayer",function($){var ALMOST_DONE_FRAC_LIMIT=0.99;
var isFirefox=navigator.userAgent.match(/Firefox\/(\d+)/);
var BUFFER_DONE_FRAC_LIMIT=isFirefox?0.4:0.2;
var MIN_FLASH_VERSION="9.0.0";
var player_callbacks={};
var VideoBuffered="VideoPlayer.VideoBuffered";
var VideoEnded="VideoPlayer.VideoEnded";
var VideoFinishedDownload="VideoPlayer.VideoFinishedDownload";
var VideoError="VideoPlayer.VideoError";
var Html5VideoReadyMetrics="VideoPlayer.Html5VideoReadyMetrics";
var FlashVideoReadyMetrics="VideoPlayer.FlashVideoReadyMetrics";
var FlashPlayerLoadedMetrics="VideoPlayer.FlashPlayerLoadedMetrics";
var VideoNoFlashError="VideoPlayer.VideoNoFlashError";
var isMobile=navigator.userAgent.match(/Mobile/i);
var isIpad=navigator.userAgent.match(/ipad/i);
var isAndroid=navigator.userAgent.match(/cloud9|android|silk-accelerated/i);
var videoReadyMetricsDone=0;
var isIE=navigator.userAgent.match(/msie/i);
var boundHandlers={};
function bind(eventName,callback){var handlers=boundHandlers[eventName];
if(!handlers){handlers=boundHandlers[eventName]=[];
}handlers.push(callback);
}function trigger(eventName,videoPlayer){var handlers=boundHandlers[eventName];
if(!handlers){return;
}$.each(handlers,function(){this(videoPlayer);
});
}window.VideoPlayer=function(options){var defaults={loopVideo:false};
options=$.extend(defaults,options);
var self=this;
var loaded=false;
var useVideoTag=false;
var container=null;
var innerVideoContainer=null;
var flash_object=null;
var videoObj=null;
var onload=null;
var loaded_url=null;
var isFadingOut=false;
var videoIsReady=false;
var videoLoaded=0;
var userWmode="opaque";
this.id=function(){return options.id;
};
this.load=function(url){onload=function(){self.load(url);
};
if(!loaded){return;
}handleLoad(url);
};
this.play=function(url){onload=function(){self.play(url);
};
if(!loaded){return;
}handleLoad(url);
if(useVideoTag){$(videoObj).show();
container.show();
if(isAndroid){videoObj.load();
videoObj.play();
}$(videoObj).bind("canplaythrough",function(){container.css("z-index",8);
videoObj.play();
window.videoReady(options.id);
});
$(videoObj).bind("loadeddata",function(){$(videoObj).css("opacity","");
});
if(videoObj.readyState<videoObj.HAVE_CURRENT_DATA){$(videoObj).css("opacity",0);
}if(videoObj.readyState>=videoObj.HAVE_ENOUGH_DATA){container.css("z-index",8);
videoObj.play();
window.videoReady(options.id);
}}else{if(typeof flash_object.playVideo=="function"){try{flash_object.playVideo();
}catch(e){}}}};
this.resizeVideo=function(width,height){options.width=width;
options.height=height;
container.css({width:width+"px",height:height+"px"});
if(videoObj){$(videoObj).attr({width:options.width});
if(!isIE){$(videoObj).attr({height:options.height});
}}};
this.writePreplayHtml=function(){slateImage=$('<div class="slateImage" style="z-index:5" ><img src="'+options.slateImageSrc+'" /></div>').appendTo(container);
innerVideoContainer=$("<div class='innerVideoContainer' style='height:100%;width:100%;position:absolute;top:0;left:0;z-index:8;'></div>").appendTo(container);
};
this.hide=function(){container.css("z-index",2);
if(!loaded){return;
}if(useVideoTag){videoObj.pause();
$(videoObj).stop(true,true);
isFadingOut=false;
}else{if(typeof flash_object.pauseVideo=="function"){try{flash_object.pauseVideo();
}catch(e){}}}};
player_callbacks[options.id]={videoPlayerLoaded:function(){if(flash_object&&!flash_object.playVideo){$(flash_object).remove();
load_flash_player();
return;
}loaded=true;
loaded_url=null;
videoIsReady=false;
if(onload){onload();
}},videoReady:function(){if(videoReadyMetricsDone==0){if(useVideoTag){trigger(Html5VideoReadyMetrics,self);
}else{trigger(FlashVideoReadyMetrics,self);
}videoReadyMetricsDone=1;
}if(userWmode=="direct"||videoLoaded){container.css("z-index",8);
}if(videoIsReady){return;
}videoIsReady=true;
trigger(VideoBuffered,self);
},videoComplete:function(){loaded_url=null;
trigger(VideoEnded,self);
},videoLoadingProgress:function(loadedFraction){if(loadedFraction>ALMOST_DONE_FRAC_LIMIT){trigger(VideoFinishedDownload,self);
}if(!videoLoaded&&loadedFraction>BUFFER_DONE_FRAC_LIMIT){container.css("z-index",8);
videoLoaded=1;
}}};
function handleLoad(url){if(loaded_url!=url){videoIsReady=false;
if(useVideoTag){if(!/\.(mp4|m4v)$/.test(url)){loaded_url=url;
$(videoObj).trigger("error");
return;
}$(videoObj).unbind("loadeddata");
$(videoObj).unbind("canplaythrough");
if(videoObj.src==url&&videoObj.ended){videoIsReady=true;
videoObj.currentTime=0.01;
}else{videoObj.src=url;
videoObj.load();
}}else{if(typeof flash_object.loadVideo=="function"){try{flash_object.loadVideo(url);
}catch(e){}}}loaded_url=url;
}if(videoIsReady){videoIsReady=false;
window.videoReady(options.id);
}}function load_flash_player(){if(/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent)){var ffversion=new Number(RegExp.$1);
if(ffversion<4&&ffversion>=3){userWmode="direct";
}}if(swfobject.hasFlashPlayerVersion(MIN_FLASH_VERSION)){var flashvars={loop:options.loopVideo,buffer:4,player_id:options.id};
var params={allowScriptAccess:"always",wmode:userWmode,quality:"high",bgcolor:"#FFFFFF",menu:"false",allowfullscreen:"false"};
var attributes={id:"video_swf_"+options.id,name:"video_swf_"+options.id};
var placeholderID=options.id+"-placeholder";
if(window.ImageBlockWeblabs&&window.ImageBlockWeblabs.swipe){$("<div>").appendTo(innerVideoContainer).attr({id:placeholderID});
}else{$("<div>").appendTo(container).attr({id:placeholderID});
}swfobject.embedSWF(options.swf,placeholderID,"100%","100%",MIN_FLASH_VERSION,null,flashvars,params,attributes,function(e){if(e.success){flash_object=e.ref;
if($.browser.msie){setTimeout(function(){trigger(FlashPlayerLoadedMetrics,self);
},10);
}else{trigger(FlashPlayerLoadedMetrics,self);
}}else{trigger(VideoError,self);
}});
self.enabled=true;
}else{trigger(VideoNoFlashError,self);
}}function isChromeBrowser(){return navigator.userAgent.search(/chrome/i)!=-1;
}function initialize(){container=$("#"+options.id);
self.resizeVideo(options.width,options.height);
container.css("z-index",2);
var videoElem=$("<video>");
if((true==isChromeBrowser())||(!videoElem.get(0).play)){load_flash_player();
return;
}useVideoTag=true;
videoObj=videoElem.get(0);
videoElem.attr({width:options.width});
if(!isIE){$(videoObj).attr({height:options.height});
}videoElem.bind("error",function(){useVideoTag=false;
loaded=false;
loaded_url=null;
videoElem.unbind("error ended waiting timeupdate loadeddata canplaythrough").remove();
load_flash_player();
});
videoElem.bind("progress",function(){var ranges=videoObj.buffered;
var loaded=0;
if(ranges.length>0&&ranges.start(0)==0){loaded=ranges.end(0);
}window.videoLoadingProgress(options.id,loaded,videoObj.duration);
});
videoElem.bind("ended",function(){window.videoComplete(options.id);
});
if(!isMobile){videoElem.bind("timeupdate",function(){if(isFadingOut){return;
}var fadeOutTime=0.75;
var timeRemaining=this.duration-this.currentTime;
if(timeRemaining<fadeOutTime){isFadingOut=true;
videoElem.fadeOut(timeRemaining*1000,function(){isFadingOut=false;
});
}});
}container.hide();
container.append(videoElem);
self.enabled=true;
if(isMobile){VideoPlayer.videoOnLanding=false;
}window.videoPlayerLoaded(options.id);
}initialize();
};
window.VideoPlayer.bindBuffered=function(callback){bind(VideoBuffered,callback);
};
window.VideoPlayer.bindEnded=function(callback){bind(VideoEnded,callback);
};
window.VideoPlayer.bindFinishedDownload=function(callback){bind(VideoFinishedDownload,callback);
};
window.VideoPlayer.bindError=function(callback){bind(VideoError,callback);
};
window.VideoPlayer.bindNoFlashError=function(callback){bind(VideoNoFlashError,callback);
};
window.VideoPlayer.bindHtml5Ready=function(callback){bind(Html5VideoReadyMetrics,callback);
};
window.VideoPlayer.bindFlashReady=function(callback){bind(FlashVideoReadyMetrics,callback);
};
window.VideoPlayer.bindPlayerLoaded=function(callback){bind(FlashPlayerLoadedMetrics,callback);
};
window.VideoPlayer.videoOnLanding=true;
window.videoPlayerLoaded=function(id){player_callbacks[id].videoPlayerLoaded();
};
window.videoReady=function(id){player_callbacks[id].videoReady();
};
window.videoComplete=function(id){player_callbacks[id].videoComplete();
};
window.videoLoadingProgress=function(id,bytesLoaded,bytesTotal){player_callbacks[id].videoLoadingProgress(bytesLoaded/bytesTotal);
};
});
P.when("A","jQuery","imageBlockUtils","ImageBlockATF","ImageBlockBTF","chromelessVideoPlayer","immersiveView","imageBlockLogger").execute(function(A,$,imageBlockUtils,imageBlockInitialData,imageBlockData,chromelessVideoPlayer,immersiveView,imageBlockLogger){function ImageBlock(options,imageBlockUtils){var isAndroid=navigator.userAgent.match(/cloud9|android|silk-accelerated/i);
options.useHoverZoom=options.useHoverZoom&&!isAndroid;
var magnifier,landingColor=options.defaultColor,currentItem={"color":options.defaultColor,"type":"image","index":0,"thumbnailIndex":0},colorImages=options.colorImages,canvas=$("#imageBlock .canvas"),itemContainer=$("#main-image-container"),utils=imageBlockUtils.init(options),videoSizes=options.mainImageSizes,thumbs=$("#imageBlock #altImages ul"),videoPlayers={},useChromelessVideoPlayer=options.useChromelessVideoPlayer,isIpad=navigator.userAgent.match(/ipad/i),flashNotInstalled=0,videoHolderRatio=0,videoHolderHeight=0,videoHolderWidth=0,isFirstImageCaption=true,logger=new window.ImageBlockclientLogger("ImageBlockUDP",true);
if(options.isDebug&&window.console){console.log(options);
}initialize();
function initialize(){if(useChromelessVideoPlayer){onVideoPlayerLoaded();
}setupInteraction();
P.when("dpf").execute(imageBlockTwisterInitialization);
if(amznJQ){amznJQ.available("dpf",imageBlockTwisterInitialization);
}$(window).resize(resizeCallback);
A.on("image-block-select-thumbnail",function(obj){if(typeof obj==="undefined"){return;
}if(obj.length<=0){return;
}if(isIpad){obj.click();
}else{obj.mouseover();
}});
createAndAddNewThumbnails(currentItem.color,true);
calculateHolderSize();
if(options.autoplayVideo){A.trigger("image-block-select-thumbnail",thumbs.find("img:last"));
}else{A.trigger("image-block-select-thumbnail",thumbs.find("img:first"));
}displayHandSymbolIfApplicable();
}function setupInteraction(){A.declarative("thumb-action",["click",isIpad?"":"mouseenter"],selectThumbnail);
A.declarative("thumb-action",["mouseleave"],thumbImageLeave);
A.declarative("main-image-click",["click"],mainImageClick);
A.declarative("main-image-click",["mouseenter","mouseleave"],mainImageHover);
A.declarative("main-video-click",["click"],function(event){A.trigger("mainVideoClick",event);
});
}function imageBlockTwisterInitialization(){var dpState=DetailPage.StateController.getState();
var initialColor=utils.getColorFromState(dpState["selected_variations"]);
if(initialColor&&initialColor!=""&&getMainImageHash(initialColor,0)!=-1){setCurrentItem(initialColor);
utils.setLandingColor(initialColor);
}A.on("image-block-twister-swatch-hover",updateMainBlockForHoveredVariation);
A.on("image-block-twister-swatch-click",updateAltImagesForSelectedVaration);
A.on("image-block-video-fetch-completed",createAndAddNewThumbnails);
}function resizeCallback(e){var videos=utils.getVideos(currentItem.color);
if($.isArray(videos)){$.each(videos,function(){this.preplayResizePending=true;
});
}utils.resizeHappened();
resizeMainBlockItem();
}function resizeMainBlockItem(){var imgWrappers=canvas.find(".item .imgTagWrapper");
var mainBlockHeight=utils.getMainBlockHeight();
if(mainBlockHeight>0){imgWrappers.height(mainBlockHeight);
}var $dynamicImages=canvas.find("img.a-dynamic-image");
$dynamicImages.each(function(){var $t=$(this);
if($t.data("a-manual-replacement")){var url=utils.loadDynamicImage(this);
if(url){$t.attr("src",url);
}}var maxHeight,maxWidth;
if(options.useStretchyImageFix){var mainImageHash=$t.data("a-dynamic-image");
maxHeight=utils.getMaxHeightOfMainImage(mainImageHash);
maxWidth=utils.getMaxWidthOfMainImage(mainImageHash);
}else{maxHeight=itemContainer.height();
maxWidth=itemContainer.width();
}var curStyle="max-height: "+maxHeight+"px;"+" max-width: "+maxWidth+"px;";
$t.attr("style",curStyle);
});
if(useChromelessVideoPlayer){resizeChromelessVideos(videoPlayers);
}if(currentItem.type=="chromeful-video"){var video=utils.getVideos(currentItem.color)[currentItem.index];
if(video&&video.preplayResizePending){resizeVideo(video);
}}loadMagnifier();
}function resizeChromelessVideos(videoPlayers){if(canvas.find(".chromeless-video").length<=0){return;
}calculateHolderSize();
var slateImage=canvas.find(".chromeless-video .slateImage").get(0);
setSlateImageDimensions(slateImage);
var isVideoPlaying=canvas.find(".chromeless-video.selected");
if(isVideoPlaying){canvas.find(".chromeless-video.selected").addClass("resized");
var videoHolderId=canvas.find(".video").attr("id");
if(videoHolderId){if(videoPlayers[videoHolderId]){videoPlayers[videoHolderId].resizeVideo(videoHolderWidth,videoHolderHeight);
}}}else{var isResized=canvas.find(".chromeless-video.resized");
if(isResized){getCorrectVideoHeightAndWidth();
}}}function getCorrectVideoHeightAndWidth(){var slateImage=canvas.find(".chromeless-video").find("img");
if(slateImage){videoPlayers={};
slateImageHeight=slateImage.height();
slateImageWidth=slateImage.width();
if(slateImageHeight>0&&slateImageWidth>0){videoHolderWidth=slateImageWidth;
videoHolderHeight=slateImageHeight;
}slateImage.removeClass("resized");
}}function calculateHolderSize(){var containerHeight=itemContainer.height();
var maxHeight=0;
var maxWidth=0;
$.each(videoSizes,function(id,sizes){var width=sizes[0];
var height=sizes[1];
if(width>maxWidth){maxWidth=width;
maxHeight=height;
}});
if(maxHeight!=0){videoHolderRatio=maxWidth/maxHeight;
}containerHeight=Math.min(containerHeight,maxHeight);
if(containerHeight!=0){videoHolderHeight=containerHeight;
videoHolderWidth=videoHolderHeight*videoHolderRatio;
}}function resizeVideo(video){var containerWidth=itemContainer.width(),containerHeight=itemContainer.height();
var maxWidth=utils.getMaxWidthOfSlateImages(video.main);
var playerWidth=Math.min(maxWidth,containerWidth,containerHeight);
var playerHeight=playerWidth;
var playerWidth=Math.min(maxWidth,containerWidth,containerHeight),playerHeight=playerWidth;
if(video&&video.player){var flashShowing=!$("#"+video.player.preplayDivId).is(":visible");
if(flashShowing){video.player.resizeVideo(playerWidth,playerHeight);
}else{video.slateImageUrl=utils.getBestUrlForAvailableWidth(video.main);
video.player.preplayWidth=playerWidth;
video.player.preplayHeight=playerHeight;
video.player.flashDivWidth=playerWidth;
video.player.flashDivHeight=playerHeight;
video.player.preplayobject=undefined;
video.player.showPreplay();
video.preplayResizePending=false;
}}}function createThumbnail(type,data,index,thumbnailIndex,isFirstInteraction){var item=thumbs.find(".template").clone().removeClass("template").addClass("item");
var thumb=$("<img />").attr("src",data.thumb);
if(options.autoplayVideo&&isFirstInteraction){if(type=="chromeless-video"){item.find(".a-button").addClass("a-button-selected");
}}else{if(thumbnailIndex==0){item.find(".a-button").addClass("a-button-selected");
}}item.find(".placeHolder").replaceWith(thumb);
item.find(".a-declarative").attr("data-thumb-action",'{"index":"'+index+'", "thumbnailIndex":"'+thumbnailIndex+'", "type": "'+type+'"}');
return item;
}function createAndAddNewThumbnails(newColor,isFirstInteraction){thumbs.find(".item").remove();
var thumbnailIndex=0,images=colorImages[newColor],videos=utils.getVideos(newColor),videoReserve=videos.length>0&&options.alwaysIncludeVideo?1:0;
$.each(images,function(index,data){if(thumbnailIndex>=(options.maxAlts-videoReserve)){return false;
}var item=createThumbnail("image",data,index,thumbnailIndex,isFirstInteraction);
thumbs.append(item);
thumbnailIndex++;
});
$.each(videos,function(index,data){if(thumbnailIndex>=options.maxAlts){return false;
}data.thumb=options.staticImages.videoThumbIcon;
if(useChromelessVideoPlayer){var item=createThumbnail("chromeless-video",data,index,thumbnailIndex,isFirstInteraction);
}else{var item=createThumbnail("chromeful-video",data,index,thumbnailIndex);
}thumbs.append(item);
thumbnailIndex++;
});
}function preLoadAllCanvasItems(){var thumbnailIndex=0,images=colorImages[currentItem.color];
$.each(images,function(index,imageHash){getCanvasItemByIndex(currentItem.color,"image",index,thumbnailIndex++);
});
}function getCanvasItemByIndex(c,type,index,thumbnailIndex){var item;
if(type=="chromeless-video"){item=createChromelessVideoItem(c,index,thumbnailIndex);
return item;
}else{if(type=="chromeful-video"){item=createChromefulVideoItem(c,index,thumbnailIndex);
}else{if(canvas.find(".item.itemNo"+thumbnailIndex).length>0){item=canvas.find(".item.itemNo"+thumbnailIndex);
}else{if(type=="image"){item=createMainImageItem(c,index,thumbnailIndex);
}}}}return item;
}function setCurrentItem(c,type,index,thumbnailIndex){if(typeof c!=="undefined"){currentItem.color=c;
}if(typeof type!=="undefined"){currentItem.type=type;
}if(typeof index!=="undefined"){currentItem.index=index;
}if(typeof thumbnailIndex!=="undefined"){currentItem.thumbnailIndex=thumbnailIndex;
}}function mainImageHover(event){updateCaption(event);
}function thumbImageLeave(event){var d=event.data;
if(typeof d!=="undefined"&&typeof d.index!=="undefined"&&typeof d.thumbnailIndex!=="undefined"&&typeof d.type!=="undefined"){utils.setImageCaption(currentItem.color,d.type,d.index,d.thumbnailIndex);
}}function updateCaption(event){var mouseIn=false;
if(event.type=="mouseenter"){mouseIn=true;
}var d;
var selectedThumb=$("altImages,.a-button-selected");
if(selectedThumb!=null&&selectedThumb.parent()!=null&&selectedThumb.parent().data()!=null){d=selectedThumb.parent().data().thumbAction;
}if(typeof d!=="undefined"&&typeof d.index!=="undefined"&&typeof d.thumbnailIndex!=="undefined"&&typeof d.type!=="undefined"){utils.setImageCaption(currentItem.color,d.type,d.index,d.thumbnailIndex,0,mouseIn);
}}function displayHandSymbolIfApplicable(){if(options.useIV){canvas.css("cursor","pointer");
}}function selectThumbnail(event){var d=event.data;
if(!d){return -1;
}hideNoFlashContent();
if(typeof d.index=="undefined"||typeof d.thumbnailIndex=="undefined"||typeof d.type=="undefined"){return -1;
}var item=event.$declarativeParent.find(".a-button");
thumbs.find(".a-button").removeClass("a-button-selected");
$(item).addClass("a-button-selected");
$(item).removeClass("a-button-focus");
var mainBlockItem=getCanvasItemByIndex(currentItem.color,d.type,d.index,d.thumbnailIndex);
if(mainBlockItem!=-1){updateMainBlock(mainBlockItem);
var mouseIn=true;
if(isFirstImageCaption){isFirstImageCaption=false;
mouseIn=false;
}utils.setImageCaption(currentItem.color,d.type,d.index,d.thumbnailIndex,0,mouseIn);
setCurrentItem(currentItem.color,d.type,d.index,d.thumbnailIndex);
resizeMainBlockItem();
if(event.type=="click"){openImmersiveView(event);
}}else{utils.showUnavailableExp();
}}function updateMainBlockForHoveredVariation(id,dpState,testColor){hideNoFlashContent();
isFirstImageCaption=true;
var newColor=testColor?testColor:utils.getColorFromState(dpState.getState()["hovered_variations"]);
newColor=newColor&&newColor!=""?newColor:options.defaultColor;
var selectedColor=utils.getColorFromState(dpState.getState()["selected_variations"]);
selectedColor=selectedColor&&selectedColor!=""?selectedColor:options.defaultColor;
if(selectedColor==currentItem.color&&currentItem.color==newColor){A.trigger("image-block-select-thumbnail",thumbs.find("img:first"));
return;
}var imageHash=getMainImageHash(newColor,0);
if(imageHash==-1){var firstItem=canvas.find(".item.itemNo0");
updateMainBlock(firstItem);
utils.showUnavailableExp(newColor);
return;
}var shw=canvas.find(".swatchHoverExp"),newImage=createDynamicImage(imageHash),image=shw.find("img");
shw.find(".imgTagWrapper").html(newImage);
utils.loadImageManually(shw.find(".a-dynamic-image"));
updateMainBlock(shw,true);
}function updateAltImagesForSelectedVaration(id,dpState,onloadFunction,forceColor){hideNoFlashContent();
isFirstImageCaption=true;
var newColor=forceColor?forceColor:utils.getColorFromState(dpState.getState()["selected_variations"]);
newColor=newColor&&newColor!=""?newColor:options.defaultColor;
if(newColor==currentItem.color){if(typeof onloadFunction=="function"){onloadFunction();
}return;
}videoPlayers={};
var type="image",index=0,thumbnailIndex=0;
var item=createMainImageItem(newColor,index,thumbnailIndex,onloadFunction);
if(item==-1){utils.showUnavailableExp(newColor);
return;
}setCurrentItem(newColor,type,index,thumbnailIndex);
removeAllItems();
canvas.find(".list").append(item);
loadMagnifier();
createAndAddNewThumbnails(newColor);
}function removeAllItems(){destroyMagnifier();
canvas.find(".list .item").remove();
var videos=utils.getVideos(currentItem.color);
$.each(videos,function(){this.preplayResizePending=undefined;
this.player=undefined;
});
}function hideAllItems(){canvas.find("li").removeClass("selected");
utils.hideUnavailableExp();
if(typeof AmznVideoPlayer!="undefined"){var videoSet=utils.getVideos(currentItem.color);
$.each(videoSet,function(){if(this.player){try{this.player.pause();
}catch(e){logger.logKeyValuePair("AmznVideoPlayer.pause","exception "+e.message+" user agent "+navigator.userAgent);
}}});
}}function getMainImageHash(c,index){if(colorImages.length<1){return -1;
}if(typeof colorImages[c]=="undefined"){return -1;
}if(typeof colorImages[c][index]=="undefined"){return -1;
}if(typeof colorImages[c][index].main!=="object"){return -1;
}var keys=$.map(colorImages[c][index].main,function(value,key){return key;
});
if(keys.length<1){return -1;
}return colorImages[c][index];
}function setSlateImageDimensions(elem){if(elem){var tempHeight=videoHolderHeight;
if(isIpad){tempHeight=tempHeight+1;
}elem.style.width=tempHeight*videoHolderRatio+"px";
elem.style.height=tempHeight+"px";
}}function createChromelessVideoHolder(c,index,thumbnailIndex){var videoHash=utils.getVideos(currentItem.color)[index];
if(videoHash&&!videoHash.player||isIpad){if(!videoPlayers[videoHash.holderId]||isIpad){$("#"+videoHash.holderId).remove();
var holder=$("<div id='"+videoHash.holderId+"' class='holder video'></div>");
var item=canvas.find(".chromeless-video");
if(item.length==0){var slateImages={};
if(currentItem.color==landingColor&&options.initialColorToAsinMap){slateImageSrc=utils.getBestUrlForAvailableWidth(options.initialColorToAsinMap);
}else{slateImages.main=utils.getSlateImage(currentItem.color);
}var imageHolder=createDynamicImage(slateImages,true);
canvas.find(".selected").removeClass("selected");
item=canvas.find(".mainImageTemplate").clone().removeClass("template mainImageTemplate").addClass("item chromeless-video itemNo"+thumbnailIndex+" selected maintain-height");
item.find(".placeHolder").replaceWith(imageHolder);
canvas.find(".list").append(item);
utils.loadImageManually(item.find(".a-dynamic-image"));
var slateImage=item.find(".imgTagWrapper .slateImage").get(0);
setSlateImageDimensions(slateImage);
}item=canvas.find(".chromeless-video");
if(flashNotInstalled){item.addClass("noflash");
showNoFlashContent();
}item.find(".a-declarative .imgTagWrapper").append(holder);
holder.click(function(){return false;
});
var slateImageSrc="";
if(currentItem.color==landingColor&&options.initialColorToAsinMap){slateImageSrc=utils.getBestUrlForAvailableWidth(options.initialColorToAsinMap);
}else{slateImageSrc=utils.getBestUrlForAvailableWidth(utils.getSlateImage(currentItem.color));
}videoPlayers[videoHash.holderId]=new VideoPlayer({id:videoHash.holderId,width:videoHolderWidth,height:videoHolderHeight,swf:options.staticImages.videoSWFPath,slateImageSrc:slateImageSrc});
videoPlayers[videoHash.holderId].load(videoHash.url);
}videoHash.player=videoPlayers[videoHash.holderId];
}else{item=canvas.find(".itemNo"+thumbnailIndex);
if(flashNotInstalled){item.addClass("noflash");
showNoFlashContent();
}}return item;
}function createChromelessVideoItem(c,index,thumbnailIndex){var videoHash=utils.getVideos(currentItem.color)[index];
if(typeof videoHash=="undefined"){return -1;
}var itemHolder;
if(typeof videoHash=="undefined"){return -1;
}itemHolder=createChromelessVideoHolder(c,index,thumbnailIndex);
currentHolder=$("#"+videoHash.holderId);
videoHash.player=videoPlayers[videoHash.holderId];
if(typeof(videoHash.player)!="undefined"){videoHash.player.play(videoHash.url);
}return itemHolder;
}function onVideoPlayerLoaded(){VideoPlayer.bindEnded(function(videoPlayer){var videoHash=utils.getVideos(currentItem.color)[0];
if(videoPlayers[videoHash.holderId]){A.trigger("image-block-select-thumbnail",thumbs.find("img:first"));
}});
VideoPlayer.bindHtml5Ready(function(){videoReadyTriggered=1;
logger.logKeyValuePair("ChromelessVideo","HTML5");
});
VideoPlayer.bindFlashReady(function(){logger.logKeyValuePair("ChromelessVideo","FLASH");
});
VideoPlayer.bindFinishedDownload(function(){videoDownloadedTriggered=1;
});
VideoPlayer.bindNoFlashError(function(){flashNotInstalled=1;
A.trigger("image-block-select-thumbnail",thumbs.find("img:first"));
logger.logKeyValuePair("ChromelessVideo","NO_FLASH_ERROR");
});
VideoPlayer.bindError(function(){A.trigger("image-block-select-thumbnail",thumbs.find("img:first"));
logger.logKeyValuePair("ChromelessVideo","ERROR");
});
}function createChromefulVideoItem(c,index,thumbnailIndex){if(!window.AmznVideoPlayer){return;
}var item,video=utils.getVideos(currentItem.color)[index];
if(!video){return -1;
}if(!video.main){return -1;
}var holderId=video.holderId;
utils.stopLastPlayingVideo();
var thumb=canvas.find(".item.itemNo"+thumbnailIndex);
if(thumb.find("#"+holderId).length){item=canvas.find(".itemNo"+thumbnailIndex);
video.player.writePreplayHtml();
$("#preplayDiv"+video.mediaObjectId).css("display","block");
}else{thumb.remove();
$("#"+holderId).remove();
var containerWidth=itemContainer.width(),containerHeight=itemContainer.height();
var maxWidth=utils.getMaxWidthOfSlateImages(video.main);
var playerWidth=Math.min(maxWidth,containerWidth,containerHeight);
var playerHeight=playerWidth;
var holder=$("<div id='"+video.holderId+"'></div>");
item=canvas.find(".mainImageTemplate").clone().removeClass("template mainImageTemplate").addClass("chromeful-video item itemNo"+thumbnailIndex);
item.find(".placeHolder").replaceWith(holder);
canvas.find(".list").append(item);
video.slateImageUrl=utils.getBestUrlForAvailableWidth(video.main);
video.player=new AmznVideoPlayer(video,video.holderId,playerWidth,playerHeight);
video.player.writePreplayHtml();
holder.click(function(){return false;
});
}return item;
}function showNoFlashContent(){if(flashNotInstalled){canvas.find(".noFlash").removeClass("a-hidden");
}}function hideNoFlashContent(){if(flashNotInstalled){canvas.find(".noFlash").addClass("a-hidden");
}}function createMainImageItem(c,index,thumbnailIndex,onloadEvent){var imageHash=getMainImageHash(c,index);
if(imageHash==-1){return -1;
}var item=canvas.find(".mainImageTemplate").clone().removeClass("template mainImageTemplate").addClass("image item itemNo"+thumbnailIndex+" maintain-height");
var image=createDynamicImage(imageHash,false,onloadEvent);
item.find(".placeHolder").replaceWith(image);
canvas.find(".list").append(item);
utils.loadImageManually(item.find(".a-dynamic-image"));
return item;
}function createDynamicImage(imageHash,isChromeless,onloadEvent){var bestImageUrl;
var stretchDirection;
var boundImage="";
$.each(imageHash.main,function(url,size){if(typeof bestImageUrl=="undefined"){bestImageUrl=url;
}if(options.shouldApplyResizeFix){if(size[1]>0&&parseFloat(size[0]/size[1])<parseFloat(options.holderRatio)&&typeof stretchDirection=="undefined"){stretchDirection="a-stretch-vertical";
}else{if(typeof stretchDirection=="undefined"){stretchDirection="a-stretch-horizontal";
}}}else{if(size[1]>0&&parseFloat(size[0]/size[1])<=parseFloat(options.holderRatio)&&typeof stretchDirection=="undefined"){stretchDirection="a-stretch-vertical";
}else{if(typeof stretchDirection=="undefined"){stretchDirection="a-stretch-horizontal";
}}}});
var classes=" a-dynamic-image ";
if(isChromeless){classes=classes+"slateImage";
}else{classes=classes+stretchDirection;
}var maxHeight,maxWidth;
if(options.useStretchyImageFix){maxHeight=utils.getMaxHeightOfMainImage(imageHash.main);
maxWidth=utils.getMaxWidthOfMainImage(imageHash.main);
}else{maxHeight=itemContainer.height();
maxWidth=itemContainer.width();
}boundImage="max-height: "+maxHeight+"px;"+" max-width: "+maxWidth+"px;";
var image=$("<div />");
image.attr({"data-a-dynamic-image":JSON.stringify(imageHash.main),"data-old-hires":imageHash.hiRes,"class":classes,"data-a-manual-replacement":"true","style":boundImage,"onload":(typeof onloadEvent!="undefined")?onloadEvent:""});
return image;
}function updateMainBlock(mainBlockItem,noMagnifier){if(typeof mainBlockItem=="undefined"){return -1;
}hideAllItems();
var containerElem=itemContainer.get(0);
if(containerElem.style&&containerElem.style.height){var imgWrapper=mainBlockItem.find(".imgTagWrapper").get(0);
imgWrapper.style.height=containerElem.style.height;
}mainBlockItem.addClass("selected");
if(!noMagnifier){loadMagnifier();
}}function mainImageClick(event){openImmersiveView(event);
}function openImmersiveView(e){immersiveView.iVController(e,options,utils,logger);
}function destroyMagnifier(){if(magnifier){magnifier.destroy();
magnifier=undefined;
}}function loadMagnifier(){if(!options.useHoverZoom){return;
}var logMetrics=null;
P.when("imageMagnifier").execute(function(im){var opts={adjustment:[0,0,1,1],generalImageUrls:options.staticImages,location:"over",minHeightElement:"#imageBlock",preload:"ready",zIndex:190,useHoverZoomIpad:options.useHoverZoomIpad,useHoverZoom:options.useHoverZoom,logMetrics:logMetrics};
destroyMagnifier();
var navImage=canvas.find(".image.item.selected img[data-old-hires]");
if(navImage.length>0){magnifier=navImage.amazonMagnifier(opts);
}});
}}if(imageBlockData&&imageBlockData["colorImages"]&&imageBlockInitialData&&imageBlockInitialData["colorImages"]){imageBlockData["colorImages"]["initial"]=imageBlockInitialData["colorImages"]["initial"];
imageBlockData["colorImages"][imageBlockData.landingAsinColor]=imageBlockInitialData["colorImages"]["initial"];
}if(imageBlockData&&imageBlockData["colorImages"]&&imageBlockInitialData&&imageBlockInitialData["colorToAsin"]&&imageBlockInitialData["colorToAsin"]["initial"]&&imageBlockInitialData["colorToAsin"]["initial"][0]){imageBlockData["initialColorToAsinMap"]=imageBlockInitialData["colorToAsin"]["initial"][0].main;
}if(imageBlockData&&imageBlockInitialData["holderRatio"]){imageBlockData["holderRatio"]=imageBlockInitialData["holderRatio"];
}else{imageBlockData["holderRatio"]=1;
}imageBlockData["holderMaxHeight"]=imageBlockInitialData["holderMaxHeight"];
imageBlockData["useStretchyImageFix"]=imageBlockInitialData["useStretchyImageFix"];
var imageBlock=new ImageBlock(imageBlockData,imageBlockUtils);
});
